import { describe, expect, it } from 'vitest'
import type {
  CodexSessionCreateOptions as CodexSessionCreateOptionsContract,
  CodexSessionLifecycleEvent as CodexSessionLifecycleEventContract,
  CodexSessionTargetUpdateResult as CodexSessionTargetUpdateResultContract
} from '../src/shared/contracts/codexSessions'
import type {
  CodexSessionCreateOptions as CodexSessionCreateOptionsPreload,
  CodexSessionLifecycleEvent as CodexSessionLifecycleEventPreload,
  CodexSessionTargetUpdateResult as CodexSessionTargetUpdateResultPreload
} from '../src/shared/preload'
import type {
  TerminalCreateOptions as TerminalCreateOptionsContract,
  TerminalKeyboardInteractiveRequest as TerminalKeyboardInteractiveRequestContract,
  TerminalLifecycleEvent as TerminalLifecycleEventContract,
  TerminalWriteResult as TerminalWriteResultContract
} from '../src/shared/contracts/terminalSessions'
import type {
  TerminalCreateOptions as TerminalCreateOptionsPreload,
  TerminalKeyboardInteractiveRequest as TerminalKeyboardInteractiveRequestPreload,
  TerminalLifecycleEvent as TerminalLifecycleEventPreload,
  TerminalWriteResult as TerminalWriteResultPreload
} from '../src/shared/preload'
import type {
  TerminalCommandGenerationInput as TerminalCommandGenerationInputContract,
  TerminalCommandGenerationRecord as TerminalCommandGenerationRecordContract,
  TerminalCommandGenerationResult as TerminalCommandGenerationResultContract,
  TerminalCommandSuggestion as TerminalCommandSuggestionContract,
  TerminalCommandSuggestionContext as TerminalCommandSuggestionContextContract
} from '../src/shared/contracts/terminalTools'
import type {
  TerminalCommandGenerationInput as TerminalCommandGenerationInputPreload,
  TerminalCommandGenerationRecord as TerminalCommandGenerationRecordPreload,
  TerminalCommandGenerationResult as TerminalCommandGenerationResultPreload,
  TerminalCommandSuggestion as TerminalCommandSuggestionPreload,
  TerminalCommandSuggestionContext as TerminalCommandSuggestionContextPreload
} from '../src/shared/preload'
import type {
  AiopsAssetImportPreviewResult as AiopsAssetImportPreviewResultContract,
  AiopsAssetInput as AiopsAssetInputContract,
  AiopsAssetSnapshot as AiopsAssetSnapshotContract,
  AiopsSshTunnelMutationResult as AiopsSshTunnelMutationResultContract
} from '../src/shared/contracts/assets'
import type {
  AiopsAssetImportPreviewResult as AiopsAssetImportPreviewResultPreload,
  AiopsAssetInput as AiopsAssetInputPreload,
  AiopsAssetSnapshot as AiopsAssetSnapshotPreload,
  AiopsSshTunnelMutationResult as AiopsSshTunnelMutationResultPreload
} from '../src/shared/preload'
import type {
  AiAgentSessionEvent as AiAgentSessionEventContract,
  AgentHibernationConfigResult as AgentHibernationConfigResultContract,
  ManagedAiNotificationMutationResult as ManagedAiNotificationMutationResultContract,
  ManagedAiSessionMutationResult as ManagedAiSessionMutationResultContract
} from '../src/shared/contracts/managedAiSessions'
import type {
  AiAgentSessionEvent as AiAgentSessionEventPreload,
  AgentHibernationConfigResult as AgentHibernationConfigResultPreload,
  ManagedAiNotificationMutationResult as ManagedAiNotificationMutationResultPreload,
  ManagedAiSessionMutationResult as ManagedAiSessionMutationResultPreload
} from '../src/shared/preload'
import type {
  AgentHookInstallerOperationResult as AgentHookInstallerOperationResultContract,
  AgentHookInstallerStatus as AgentHookInstallerStatusContract
} from '../src/shared/contracts/agentHooks'
import type {
  AgentHookInstallerOperationResult as AgentHookInstallerOperationResultPreload,
  AgentHookInstallerStatus as AgentHookInstallerStatusPreload
} from '../src/shared/preload'
import type {
  ZmodemStreamOpenResult as ZmodemStreamOpenResultContract,
  ZmodemUploadPickResult as ZmodemUploadPickResultContract
} from '../src/shared/contracts/zmodem'
import type {
  ZmodemStreamOpenResult as ZmodemStreamOpenResultPreload,
  ZmodemUploadPickResult as ZmodemUploadPickResultPreload
} from '../src/shared/preload'
import type {
  FileListEntry as FileListEntryContract,
  FileSessionCatalogResult as FileSessionCatalogResultContract,
  FileSessionInfo as FileSessionInfoContract,
  FileTransferOperationResult as FileTransferOperationResultContract
} from '../src/shared/contracts/files'
import type {
  FileListEntry as FileListEntryPreload,
  FileSessionCatalogResult as FileSessionCatalogResultPreload,
  FileSessionInfo as FileSessionInfoPreload,
  FileTransferOperationResult as FileTransferOperationResultPreload
} from '../src/shared/preload'
import type {
  AiopsTrustedDeviceRevokeResult as AiopsTrustedDeviceRevokeResultContract,
  AiopsUserAccountResult as AiopsUserAccountResultContract,
  AiopsUserLoginInput as AiopsUserLoginInputContract,
  AiopsUserMutationResult as AiopsUserMutationResultContract
} from '../src/shared/contracts/userAccount'
import type {
  AiopsTrustedDeviceRevokeResult as AiopsTrustedDeviceRevokeResultPreload,
  AiopsUserAccountResult as AiopsUserAccountResultPreload,
  AiopsUserLoginInput as AiopsUserLoginInputPreload,
  AiopsUserMutationResult as AiopsUserMutationResultPreload
} from '../src/shared/preload'
import type {
  ExtensionInstallProgress as ExtensionInstallProgressContract,
  ExtensionPackageDownloadResult as ExtensionPackageDownloadResultContract,
  ExtensionPluginOperationResult as ExtensionPluginOperationResultContract,
  ExtensionPluginRuntimeConfig as ExtensionPluginRuntimeConfigContract,
  ExtensionUserConfig as ExtensionUserConfigContract
} from '../src/shared/contracts/extensions'
import type {
  ExtensionInstallProgress as ExtensionInstallProgressPreload,
  ExtensionPackageDownloadResult as ExtensionPackageDownloadResultPreload,
  ExtensionPluginOperationResult as ExtensionPluginOperationResultPreload,
  ExtensionPluginRuntimeConfig as ExtensionPluginRuntimeConfigPreload,
  ExtensionUserConfig as ExtensionUserConfigPreload
} from '../src/shared/preload'
import type {
  QuickCommandScriptPlanResult as QuickCommandScriptPlanResultContract,
  QuickCommandSnippetMutationResult as QuickCommandSnippetMutationResultContract,
  QuickCommandSnippetSaveInput as QuickCommandSnippetSaveInputContract,
  QuickCommandsUserConfig as QuickCommandsUserConfigContract
} from '../src/shared/contracts/quickCommands'
import type {
  QuickCommandScriptPlanResult as QuickCommandScriptPlanResultPreload,
  QuickCommandSnippetMutationResult as QuickCommandSnippetMutationResultPreload,
  QuickCommandSnippetSaveInput as QuickCommandSnippetSaveInputPreload,
  QuickCommandsUserConfig as QuickCommandsUserConfigPreload
} from '../src/shared/preload'
import type {
  AliasCommandConfig as AliasCommandConfigContract,
  AliasCommandDeleteInput as AliasCommandDeleteInputContract,
  AliasCommandDeleteResult as AliasCommandDeleteResultContract,
  AliasCommandListResult as AliasCommandListResultContract,
  AliasCommandMutationResult as AliasCommandMutationResultContract,
  AliasCommandSaveInput as AliasCommandSaveInputContract
} from '../src/shared/contracts/aliases'
import type {
  AliasCommandConfig as AliasCommandConfigPreload,
  AliasCommandDeleteInput as AliasCommandDeleteInputPreload,
  AliasCommandDeleteResult as AliasCommandDeleteResultPreload,
  AliasCommandListResult as AliasCommandListResultPreload,
  AliasCommandMutationResult as AliasCommandMutationResultPreload,
  AliasCommandSaveInput as AliasCommandSaveInputPreload
} from '../src/shared/preload'
import type {
  McpConfigFile as McpConfigFileContract,
  McpConfigWriteResult as McpConfigWriteResultContract,
  McpResourceReadInput as McpResourceReadInputContract,
  McpResourceReadResult as McpResourceReadResultContract,
  McpServerUserConfig as McpServerUserConfigContract,
  McpToolCallInput as McpToolCallInputContract,
  McpToolCallResult as McpToolCallResultContract
} from '../src/shared/contracts/mcp'
import type {
  McpConfigFile as McpConfigFilePreload,
  McpConfigWriteResult as McpConfigWriteResultPreload,
  McpResourceReadInput as McpResourceReadInputPreload,
  McpResourceReadResult as McpResourceReadResultPreload,
  McpServerUserConfig as McpServerUserConfigPreload,
  McpToolCallInput as McpToolCallInputPreload,
  McpToolCallResult as McpToolCallResultPreload
} from '../src/shared/preload'
import type {
  SettingsPreferencesMutationResult as SettingsPreferencesMutationResultContract,
  SettingsPreferencesResult as SettingsPreferencesResultContract,
  SettingsPreferencesSnapshot as SettingsPreferencesSnapshotContract,
  SettingsRuleDeleteResult as SettingsRuleDeleteResultContract,
  SettingsRuleSaveInput as SettingsRuleSaveInputContract,
  SettingsShortcutSaveInput as SettingsShortcutSaveInputContract,
  ShortcutUserConfig as ShortcutUserConfigContract,
  UserRuleConfig as UserRuleConfigContract
} from '../src/shared/contracts/settingsPreferences'
import type {
  SettingsPreferencesMutationResult as SettingsPreferencesMutationResultPreload,
  SettingsPreferencesResult as SettingsPreferencesResultPreload,
  SettingsPreferencesSnapshot as SettingsPreferencesSnapshotPreload,
  SettingsRuleDeleteResult as SettingsRuleDeleteResultPreload,
  SettingsRuleSaveInput as SettingsRuleSaveInputPreload,
  SettingsShortcutSaveInput as SettingsShortcutSaveInputPreload,
  ShortcutUserConfig as ShortcutUserConfigPreload,
  UserRuleConfig as UserRuleConfigPreload
} from '../src/shared/preload'
import type {
  SkillContentResult as SkillContentResultContract,
  SkillDeleteResult as SkillDeleteResultContract,
  SkillEnabledResult as SkillEnabledResultContract,
  SkillExportResult as SkillExportResultContract,
  SkillImportErrorCode as SkillImportErrorCodeContract,
  SkillImportResult as SkillImportResultContract,
  SkillMetadataConfig as SkillMetadataConfigContract,
  SkillUserConfig as SkillUserConfigContract,
  SkillWriteResult as SkillWriteResultContract
} from '../src/shared/contracts/skills'
import type {
  SkillContentResult as SkillContentResultPreload,
  SkillDeleteResult as SkillDeleteResultPreload,
  SkillEnabledResult as SkillEnabledResultPreload,
  SkillExportResult as SkillExportResultPreload,
  SkillImportErrorCode as SkillImportErrorCodePreload,
  SkillImportResult as SkillImportResultPreload,
  SkillMetadataConfig as SkillMetadataConfigPreload,
  SkillUserConfig as SkillUserConfigPreload,
  SkillWriteResult as SkillWriteResultPreload
} from '../src/shared/preload'
import type {
  KnowledgeBaseCreateResult as KnowledgeBaseCreateResultContract,
  KnowledgeBaseDeleteResult as KnowledgeBaseDeleteResultContract,
  KnowledgeBaseEntry as KnowledgeBaseEntryContract,
  KnowledgeBaseImportResult as KnowledgeBaseImportResultContract,
  KnowledgeBaseNodeConfig as KnowledgeBaseNodeConfigContract,
  KnowledgeBasePastedImageResult as KnowledgeBasePastedImageResultContract,
  KnowledgeBaseReadResult as KnowledgeBaseReadResultContract,
  KnowledgeBaseSearchResult as KnowledgeBaseSearchResultContract,
  KnowledgeBaseSearchStatus as KnowledgeBaseSearchStatusContract,
  KnowledgeBaseTransferProgress as KnowledgeBaseTransferProgressContract,
  KnowledgeBaseUserConfig as KnowledgeBaseUserConfigContract,
  KnowledgeBaseWriteResult as KnowledgeBaseWriteResultContract,
  KnowledgeNode as KnowledgeNodeContract,
  KnowledgeNodeType as KnowledgeNodeTypeContract
} from '../src/shared/contracts/knowledgeBase'
import type {
  KnowledgeBaseCreateResult as KnowledgeBaseCreateResultPreload,
  KnowledgeBaseDeleteResult as KnowledgeBaseDeleteResultPreload,
  KnowledgeBaseEntry as KnowledgeBaseEntryPreload,
  KnowledgeBaseImportResult as KnowledgeBaseImportResultPreload,
  KnowledgeBaseNodeConfig as KnowledgeBaseNodeConfigPreload,
  KnowledgeBasePastedImageResult as KnowledgeBasePastedImageResultPreload,
  KnowledgeBaseReadResult as KnowledgeBaseReadResultPreload,
  KnowledgeBaseSearchResult as KnowledgeBaseSearchResultPreload,
  KnowledgeBaseSearchStatus as KnowledgeBaseSearchStatusPreload,
  KnowledgeBaseTransferProgress as KnowledgeBaseTransferProgressPreload,
  KnowledgeBaseUserConfig as KnowledgeBaseUserConfigPreload,
  KnowledgeBaseWriteResult as KnowledgeBaseWriteResultPreload,
  KnowledgeNode as KnowledgeNodePreload,
  KnowledgeNodeType as KnowledgeNodeTypePreload
} from '../src/shared/preload'
import type {
  AiModelCatalog as AiModelCatalogContract,
  AiPreferencesUserConfig as AiPreferencesUserConfigContract,
  AppUpdateCheckResult as AppUpdateCheckResultContract,
  AppUpdateDownloadResult as AppUpdateDownloadResultContract,
  CustomBackgroundSaveResult as CustomBackgroundSaveResultContract,
  EditorUserConfig as EditorUserConfigContract,
  KeywordHighlightUserConfig as KeywordHighlightUserConfigContract,
  KnowledgeSearchRuntimeApplyResult as KnowledgeSearchRuntimeApplyResultContract,
  ModelProviderCheckInput as ModelProviderCheckInputContract,
  ModelSettingsUserConfig as ModelSettingsUserConfigContract,
  OpenSettingsDocumentationInput as OpenSettingsDocumentationInputContract,
  PrivacyRuntimeApplyResult as PrivacyRuntimeApplyResultContract,
  SecurityUserConfig as SecurityUserConfigContract,
  SshAgentKeychainOption as SshAgentKeychainOptionContract,
  SshProxyConfig as SshProxyConfigContract,
  TerminalUserConfig as TerminalUserConfigContract,
  WorkspaceUserConfig as WorkspaceUserConfigContract
} from '../src/shared/contracts/appRuntime'
import type {
  AiModelCatalog as AiModelCatalogPreload,
  AiPreferencesUserConfig as AiPreferencesUserConfigPreload,
  AppUpdateCheckResult as AppUpdateCheckResultPreload,
  AppUpdateDownloadResult as AppUpdateDownloadResultPreload,
  CustomBackgroundSaveResult as CustomBackgroundSaveResultPreload,
  EditorUserConfig as EditorUserConfigPreload,
  KeywordHighlightUserConfig as KeywordHighlightUserConfigPreload,
  KnowledgeSearchRuntimeApplyResult as KnowledgeSearchRuntimeApplyResultPreload,
  ModelProviderCheckInput as ModelProviderCheckInputPreload,
  ModelSettingsUserConfig as ModelSettingsUserConfigPreload,
  OpenSettingsDocumentationInput as OpenSettingsDocumentationInputPreload,
  PrivacyRuntimeApplyResult as PrivacyRuntimeApplyResultPreload,
  SecurityUserConfig as SecurityUserConfigPreload,
  SshAgentKeychainOption as SshAgentKeychainOptionPreload,
  SshProxyConfig as SshProxyConfigPreload,
  TerminalUserConfig as TerminalUserConfigPreload,
  WorkspaceUserConfig as WorkspaceUserConfigPreload
} from '../src/shared/preload'
import type {
  ChatAttachmentStageResult as ChatAttachmentStageResultContract,
  ChatImageAttachmentPrepareResult as ChatImageAttachmentPrepareResultContract,
  ChatImageAttachmentValidateResult as ChatImageAttachmentValidateResultContract,
  LocalFileReadResult as LocalFileReadResultContract,
  LocalFileWriteResult as LocalFileWriteResultContract,
  OpenDialogOptions as OpenDialogOptionsContract,
  OpenDialogResult as OpenDialogResultContract,
  SaveDialogOptions as SaveDialogOptionsContract,
  SaveDialogResult as SaveDialogResultContract
} from '../src/shared/contracts/localFiles'
import type {
  ChatAttachmentStageResult as ChatAttachmentStageResultPreload,
  ChatImageAttachmentPrepareResult as ChatImageAttachmentPrepareResultPreload,
  ChatImageAttachmentValidateResult as ChatImageAttachmentValidateResultPreload,
  LocalFileReadResult as LocalFileReadResultPreload,
  LocalFileWriteResult as LocalFileWriteResultPreload,
  OpenDialogOptions as OpenDialogOptionsPreload,
  OpenDialogResult as OpenDialogResultPreload,
  SaveDialogOptions as SaveDialogOptionsPreload,
  SaveDialogResult as SaveDialogResultPreload
} from '../src/shared/preload'
import type {
  ControlAgentTeamLaunchResult as ControlAgentTeamLaunchResultContract,
  ControlNotificationRecord as ControlNotificationRecordContract,
  ControlRequest as ControlRequestContract,
  ControlResponse as ControlResponseContract,
  ControlSessionSnapshot as ControlSessionSnapshotContract,
  ControlWorkspaceSnapshot as ControlWorkspaceSnapshotContract,
  ExternalCodexMcpConnection as ExternalCodexMcpConnectionContract,
  ExternalCodexMcpResponse as ExternalCodexMcpResponseContract
} from '../src/shared/contracts/control'
import type {
  ControlAgentTeamLaunchResult as ControlAgentTeamLaunchResultPreload,
  ControlNotificationRecord as ControlNotificationRecordPreload,
  ControlRequest as ControlRequestPreload,
  ControlResponse as ControlResponsePreload,
  ControlSessionSnapshot as ControlSessionSnapshotPreload,
  ControlWorkspaceSnapshot as ControlWorkspaceSnapshotPreload,
  ExternalCodexMcpConnection as ExternalCodexMcpConnectionPreload,
  ExternalCodexMcpResponse as ExternalCodexMcpResponsePreload
} from '../src/shared/preload'
import type {
  AiChatCancelResult as AiChatCancelResultContract,
  AiChatConversationMutationResult as AiChatConversationMutationResultContract,
  AiChatExchangeRequestInput as AiChatExchangeRequestInputContract,
  AiChatExchangeRequestResult as AiChatExchangeRequestResultContract,
  AiChatHistoryMessage as AiChatHistoryMessageContract,
  AiChatResponseResult as AiChatResponseResultContract,
  AiCommandCatalogResult as AiCommandCatalogResultContract,
  AiContentPart as AiContentPartContract,
  AiContextCatalogResult as AiContextCatalogResultContract,
  AiMcpToolCallActionResult as AiMcpToolCallActionResultContract,
  AiTodoSnapshotResult as AiTodoSnapshotResultContract
} from '../src/shared/contracts/aiChat'
import type {
  AiChatCancelResult as AiChatCancelResultPreload,
  AiChatConversationMutationResult as AiChatConversationMutationResultPreload,
  AiChatExchangeRequestInput as AiChatExchangeRequestInputPreload,
  AiChatExchangeRequestResult as AiChatExchangeRequestResultPreload,
  AiChatHistoryMessage as AiChatHistoryMessagePreload,
  AiChatResponseResult as AiChatResponseResultPreload,
  AiCommandCatalogResult as AiCommandCatalogResultPreload,
  AiContentPart as AiContentPartPreload,
  AiContextCatalogResult as AiContextCatalogResultPreload,
  AiMcpToolCallActionResult as AiMcpToolCallActionResultPreload,
  AiTodoSnapshotResult as AiTodoSnapshotResultPreload
} from '../src/shared/preload'
import type {
  DatabaseAiDrawerResponseInput as DatabaseAiDrawerResponseInputContract,
  DatabaseAiDrawerResponseResult as DatabaseAiDrawerResponseResultContract,
  DatabaseAiPaneResponseResult as DatabaseAiPaneResponseResultContract,
  DatabaseAiPaneStateSnapshot as DatabaseAiPaneStateSnapshotContract,
  DatabaseConnectionSaveInput as DatabaseConnectionSaveInputContract,
  DatabaseConnectionTestInput as DatabaseConnectionTestInputContract,
  DatabaseConnectionTestResult as DatabaseConnectionTestResultContract,
  DatabaseExportResult as DatabaseExportResultContract,
  DatabasePageCommentKey as DatabasePageCommentKeyContract,
  DatabaseSqlErrorDiagnosisInput as DatabaseSqlErrorDiagnosisInputContract,
  DatabaseSqlExecuteResult as DatabaseSqlExecuteResultContract,
  DatabaseTableMutationPlanResult as DatabaseTableMutationPlanResultContract,
  DatabaseTableQueryInput as DatabaseTableQueryInputContract,
  DatabaseWorkspaceCatalog as DatabaseWorkspaceCatalogContract
} from '../src/shared/contracts/database'
import type {
  DatabaseAiDrawerResponseInput as DatabaseAiDrawerResponseInputPreload,
  DatabaseAiDrawerResponseResult as DatabaseAiDrawerResponseResultPreload,
  DatabaseAiPaneResponseResult as DatabaseAiPaneResponseResultPreload,
  DatabaseAiPaneStateSnapshot as DatabaseAiPaneStateSnapshotPreload,
  DatabaseConnectionSaveInput as DatabaseConnectionSaveInputPreload,
  DatabaseConnectionTestInput as DatabaseConnectionTestInputPreload,
  DatabaseConnectionTestResult as DatabaseConnectionTestResultPreload,
  DatabaseExportResult as DatabaseExportResultPreload,
  DatabasePageCommentKey as DatabasePageCommentKeyPreload,
  DatabaseSqlErrorDiagnosisInput as DatabaseSqlErrorDiagnosisInputPreload,
  DatabaseSqlExecuteResult as DatabaseSqlExecuteResultPreload,
  DatabaseTableMutationPlanResult as DatabaseTableMutationPlanResultPreload,
  DatabaseTableQueryInput as DatabaseTableQueryInputPreload,
  DatabaseWorkspaceCatalog as DatabaseWorkspaceCatalogPreload
} from '../src/shared/preload'

type AssertAssignable<From, To extends From> = true

type CodexCreateOptionsPreloadMatchesContract = AssertAssignable<CodexSessionCreateOptionsContract, CodexSessionCreateOptionsPreload>
type CodexCreateOptionsContractMatchesPreload = AssertAssignable<CodexSessionCreateOptionsPreload, CodexSessionCreateOptionsContract>
type CodexLifecyclePreloadMatchesContract = AssertAssignable<CodexSessionLifecycleEventContract, CodexSessionLifecycleEventPreload>
type CodexLifecycleContractMatchesPreload = AssertAssignable<CodexSessionLifecycleEventPreload, CodexSessionLifecycleEventContract>
type CodexTargetUpdatePreloadMatchesContract = AssertAssignable<CodexSessionTargetUpdateResultContract, CodexSessionTargetUpdateResultPreload>
type CodexTargetUpdateContractMatchesPreload = AssertAssignable<CodexSessionTargetUpdateResultPreload, CodexSessionTargetUpdateResultContract>
type TerminalCreateOptionsPreloadMatchesContract = AssertAssignable<TerminalCreateOptionsContract, TerminalCreateOptionsPreload>
type TerminalCreateOptionsContractMatchesPreload = AssertAssignable<TerminalCreateOptionsPreload, TerminalCreateOptionsContract>
type TerminalLifecyclePreloadMatchesContract = AssertAssignable<TerminalLifecycleEventContract, TerminalLifecycleEventPreload>
type TerminalLifecycleContractMatchesPreload = AssertAssignable<TerminalLifecycleEventPreload, TerminalLifecycleEventContract>
type TerminalKeyboardInteractivePreloadMatchesContract = AssertAssignable<
  TerminalKeyboardInteractiveRequestContract,
  TerminalKeyboardInteractiveRequestPreload
>
type TerminalKeyboardInteractiveContractMatchesPreload = AssertAssignable<
  TerminalKeyboardInteractiveRequestPreload,
  TerminalKeyboardInteractiveRequestContract
>
type TerminalWriteResultPreloadMatchesContract = AssertAssignable<TerminalWriteResultContract, TerminalWriteResultPreload>
type TerminalWriteResultContractMatchesPreload = AssertAssignable<TerminalWriteResultPreload, TerminalWriteResultContract>
type TerminalCommandSuggestionPreloadMatchesContract = AssertAssignable<TerminalCommandSuggestionContract, TerminalCommandSuggestionPreload>
type TerminalCommandSuggestionContractMatchesPreload = AssertAssignable<TerminalCommandSuggestionPreload, TerminalCommandSuggestionContract>
type TerminalCommandSuggestionContextPreloadMatchesContract = AssertAssignable<TerminalCommandSuggestionContextContract, TerminalCommandSuggestionContextPreload>
type TerminalCommandSuggestionContextContractMatchesPreload = AssertAssignable<TerminalCommandSuggestionContextPreload, TerminalCommandSuggestionContextContract>
type TerminalCommandGenerationInputPreloadMatchesContract = AssertAssignable<TerminalCommandGenerationInputContract, TerminalCommandGenerationInputPreload>
type TerminalCommandGenerationInputContractMatchesPreload = AssertAssignable<TerminalCommandGenerationInputPreload, TerminalCommandGenerationInputContract>
type TerminalCommandGenerationRecordPreloadMatchesContract = AssertAssignable<TerminalCommandGenerationRecordContract, TerminalCommandGenerationRecordPreload>
type TerminalCommandGenerationRecordContractMatchesPreload = AssertAssignable<TerminalCommandGenerationRecordPreload, TerminalCommandGenerationRecordContract>
type TerminalCommandGenerationResultPreloadMatchesContract = AssertAssignable<TerminalCommandGenerationResultContract, TerminalCommandGenerationResultPreload>
type TerminalCommandGenerationResultContractMatchesPreload = AssertAssignable<TerminalCommandGenerationResultPreload, TerminalCommandGenerationResultContract>
type AssetInputPreloadMatchesContract = AssertAssignable<AiopsAssetInputContract, AiopsAssetInputPreload>
type AssetInputContractMatchesPreload = AssertAssignable<AiopsAssetInputPreload, AiopsAssetInputContract>
type AssetSnapshotPreloadMatchesContract = AssertAssignable<AiopsAssetSnapshotContract, AiopsAssetSnapshotPreload>
type AssetSnapshotContractMatchesPreload = AssertAssignable<AiopsAssetSnapshotPreload, AiopsAssetSnapshotContract>
type AssetImportPreviewPreloadMatchesContract = AssertAssignable<AiopsAssetImportPreviewResultContract, AiopsAssetImportPreviewResultPreload>
type AssetImportPreviewContractMatchesPreload = AssertAssignable<AiopsAssetImportPreviewResultPreload, AiopsAssetImportPreviewResultContract>
type SshTunnelMutationPreloadMatchesContract = AssertAssignable<AiopsSshTunnelMutationResultContract, AiopsSshTunnelMutationResultPreload>
type SshTunnelMutationContractMatchesPreload = AssertAssignable<AiopsSshTunnelMutationResultPreload, AiopsSshTunnelMutationResultContract>
type AiAgentSessionEventPreloadMatchesContract = AssertAssignable<AiAgentSessionEventContract, AiAgentSessionEventPreload>
type AiAgentSessionEventContractMatchesPreload = AssertAssignable<AiAgentSessionEventPreload, AiAgentSessionEventContract>
type ManagedAiSessionMutationPreloadMatchesContract = AssertAssignable<ManagedAiSessionMutationResultContract, ManagedAiSessionMutationResultPreload>
type ManagedAiSessionMutationContractMatchesPreload = AssertAssignable<ManagedAiSessionMutationResultPreload, ManagedAiSessionMutationResultContract>
type AgentHibernationConfigPreloadMatchesContract = AssertAssignable<AgentHibernationConfigResultContract, AgentHibernationConfigResultPreload>
type AgentHibernationConfigContractMatchesPreload = AssertAssignable<AgentHibernationConfigResultPreload, AgentHibernationConfigResultContract>
type ManagedAiNotificationMutationPreloadMatchesContract = AssertAssignable<ManagedAiNotificationMutationResultContract, ManagedAiNotificationMutationResultPreload>
type ManagedAiNotificationMutationContractMatchesPreload = AssertAssignable<
  ManagedAiNotificationMutationResultPreload,
  ManagedAiNotificationMutationResultContract
>
type AgentHookStatusPreloadMatchesContract = AssertAssignable<AgentHookInstallerStatusContract, AgentHookInstallerStatusPreload>
type AgentHookStatusContractMatchesPreload = AssertAssignable<AgentHookInstallerStatusPreload, AgentHookInstallerStatusContract>
type AgentHookOperationPreloadMatchesContract = AssertAssignable<AgentHookInstallerOperationResultContract, AgentHookInstallerOperationResultPreload>
type AgentHookOperationContractMatchesPreload = AssertAssignable<AgentHookInstallerOperationResultPreload, AgentHookInstallerOperationResultContract>
type ZmodemUploadPickPreloadMatchesContract = AssertAssignable<ZmodemUploadPickResultContract, ZmodemUploadPickResultPreload>
type ZmodemUploadPickContractMatchesPreload = AssertAssignable<ZmodemUploadPickResultPreload, ZmodemUploadPickResultContract>
type ZmodemStreamOpenPreloadMatchesContract = AssertAssignable<ZmodemStreamOpenResultContract, ZmodemStreamOpenResultPreload>
type ZmodemStreamOpenContractMatchesPreload = AssertAssignable<ZmodemStreamOpenResultPreload, ZmodemStreamOpenResultContract>
type FileSessionInfoPreloadMatchesContract = AssertAssignable<FileSessionInfoContract, FileSessionInfoPreload>
type FileSessionInfoContractMatchesPreload = AssertAssignable<FileSessionInfoPreload, FileSessionInfoContract>
type FileSessionCatalogPreloadMatchesContract = AssertAssignable<FileSessionCatalogResultContract, FileSessionCatalogResultPreload>
type FileSessionCatalogContractMatchesPreload = AssertAssignable<FileSessionCatalogResultPreload, FileSessionCatalogResultContract>
type FileListEntryPreloadMatchesContract = AssertAssignable<FileListEntryContract, FileListEntryPreload>
type FileListEntryContractMatchesPreload = AssertAssignable<FileListEntryPreload, FileListEntryContract>
type FileTransferOperationPreloadMatchesContract = AssertAssignable<FileTransferOperationResultContract, FileTransferOperationResultPreload>
type FileTransferOperationContractMatchesPreload = AssertAssignable<FileTransferOperationResultPreload, FileTransferOperationResultContract>
type UserAccountResultPreloadMatchesContract = AssertAssignable<AiopsUserAccountResultContract, AiopsUserAccountResultPreload>
type UserAccountResultContractMatchesPreload = AssertAssignable<AiopsUserAccountResultPreload, AiopsUserAccountResultContract>
type UserLoginInputPreloadMatchesContract = AssertAssignable<AiopsUserLoginInputContract, AiopsUserLoginInputPreload>
type UserLoginInputContractMatchesPreload = AssertAssignable<AiopsUserLoginInputPreload, AiopsUserLoginInputContract>
type UserMutationPreloadMatchesContract = AssertAssignable<AiopsUserMutationResultContract, AiopsUserMutationResultPreload>
type UserMutationContractMatchesPreload = AssertAssignable<AiopsUserMutationResultPreload, AiopsUserMutationResultContract>
type TrustedDeviceRevokePreloadMatchesContract = AssertAssignable<AiopsTrustedDeviceRevokeResultContract, AiopsTrustedDeviceRevokeResultPreload>
type TrustedDeviceRevokeContractMatchesPreload = AssertAssignable<AiopsTrustedDeviceRevokeResultPreload, AiopsTrustedDeviceRevokeResultContract>
type ExtensionRuntimePreloadMatchesContract = AssertAssignable<ExtensionPluginRuntimeConfigContract, ExtensionPluginRuntimeConfigPreload>
type ExtensionRuntimeContractMatchesPreload = AssertAssignable<ExtensionPluginRuntimeConfigPreload, ExtensionPluginRuntimeConfigContract>
type ExtensionOperationPreloadMatchesContract = AssertAssignable<ExtensionPluginOperationResultContract, ExtensionPluginOperationResultPreload>
type ExtensionOperationContractMatchesPreload = AssertAssignable<ExtensionPluginOperationResultPreload, ExtensionPluginOperationResultContract>
type ExtensionProgressPreloadMatchesContract = AssertAssignable<ExtensionInstallProgressContract, ExtensionInstallProgressPreload>
type ExtensionProgressContractMatchesPreload = AssertAssignable<ExtensionInstallProgressPreload, ExtensionInstallProgressContract>
type ExtensionDownloadPreloadMatchesContract = AssertAssignable<ExtensionPackageDownloadResultContract, ExtensionPackageDownloadResultPreload>
type ExtensionDownloadContractMatchesPreload = AssertAssignable<ExtensionPackageDownloadResultPreload, ExtensionPackageDownloadResultContract>
type ExtensionUserConfigPreloadMatchesContract = AssertAssignable<ExtensionUserConfigContract, ExtensionUserConfigPreload>
type ExtensionUserConfigContractMatchesPreload = AssertAssignable<ExtensionUserConfigPreload, ExtensionUserConfigContract>
type QuickCommandsSnapshotPreloadMatchesContract = AssertAssignable<QuickCommandsUserConfigContract, QuickCommandsUserConfigPreload>
type QuickCommandsSnapshotContractMatchesPreload = AssertAssignable<QuickCommandsUserConfigPreload, QuickCommandsUserConfigContract>
type QuickCommandSnippetSavePreloadMatchesContract = AssertAssignable<QuickCommandSnippetSaveInputContract, QuickCommandSnippetSaveInputPreload>
type QuickCommandSnippetSaveContractMatchesPreload = AssertAssignable<QuickCommandSnippetSaveInputPreload, QuickCommandSnippetSaveInputContract>
type QuickCommandSnippetMutationPreloadMatchesContract = AssertAssignable<QuickCommandSnippetMutationResultContract, QuickCommandSnippetMutationResultPreload>
type QuickCommandSnippetMutationContractMatchesPreload = AssertAssignable<QuickCommandSnippetMutationResultPreload, QuickCommandSnippetMutationResultContract>
type QuickCommandScriptPlanPreloadMatchesContract = AssertAssignable<QuickCommandScriptPlanResultContract, QuickCommandScriptPlanResultPreload>
type QuickCommandScriptPlanContractMatchesPreload = AssertAssignable<QuickCommandScriptPlanResultPreload, QuickCommandScriptPlanResultContract>
type AliasCommandPreloadMatchesContract = AssertAssignable<AliasCommandConfigContract, AliasCommandConfigPreload>
type AliasCommandContractMatchesPreload = AssertAssignable<AliasCommandConfigPreload, AliasCommandConfigContract>
type AliasSaveInputPreloadMatchesContract = AssertAssignable<AliasCommandSaveInputContract, AliasCommandSaveInputPreload>
type AliasSaveInputContractMatchesPreload = AssertAssignable<AliasCommandSaveInputPreload, AliasCommandSaveInputContract>
type AliasListResultPreloadMatchesContract = AssertAssignable<AliasCommandListResultContract, AliasCommandListResultPreload>
type AliasListResultContractMatchesPreload = AssertAssignable<AliasCommandListResultPreload, AliasCommandListResultContract>
type AliasMutationPreloadMatchesContract = AssertAssignable<AliasCommandMutationResultContract, AliasCommandMutationResultPreload>
type AliasMutationContractMatchesPreload = AssertAssignable<AliasCommandMutationResultPreload, AliasCommandMutationResultContract>
type AliasDeleteInputPreloadMatchesContract = AssertAssignable<AliasCommandDeleteInputContract, AliasCommandDeleteInputPreload>
type AliasDeleteInputContractMatchesPreload = AssertAssignable<AliasCommandDeleteInputPreload, AliasCommandDeleteInputContract>
type AliasDeleteResultPreloadMatchesContract = AssertAssignable<AliasCommandDeleteResultContract, AliasCommandDeleteResultPreload>
type AliasDeleteResultContractMatchesPreload = AssertAssignable<AliasCommandDeleteResultPreload, AliasCommandDeleteResultContract>
type McpConfigFilePreloadMatchesContract = AssertAssignable<McpConfigFileContract, McpConfigFilePreload>
type McpConfigFileContractMatchesPreload = AssertAssignable<McpConfigFilePreload, McpConfigFileContract>
type McpServerPreloadMatchesContract = AssertAssignable<McpServerUserConfigContract, McpServerUserConfigPreload>
type McpServerContractMatchesPreload = AssertAssignable<McpServerUserConfigPreload, McpServerUserConfigContract>
type McpConfigWritePreloadMatchesContract = AssertAssignable<McpConfigWriteResultContract, McpConfigWriteResultPreload>
type McpConfigWriteContractMatchesPreload = AssertAssignable<McpConfigWriteResultPreload, McpConfigWriteResultContract>
type McpToolCallInputPreloadMatchesContract = AssertAssignable<McpToolCallInputContract, McpToolCallInputPreload>
type McpToolCallInputContractMatchesPreload = AssertAssignable<McpToolCallInputPreload, McpToolCallInputContract>
type McpToolCallResultPreloadMatchesContract = AssertAssignable<McpToolCallResultContract, McpToolCallResultPreload>
type McpToolCallResultContractMatchesPreload = AssertAssignable<McpToolCallResultPreload, McpToolCallResultContract>
type McpResourceReadInputPreloadMatchesContract = AssertAssignable<McpResourceReadInputContract, McpResourceReadInputPreload>
type McpResourceReadInputContractMatchesPreload = AssertAssignable<McpResourceReadInputPreload, McpResourceReadInputContract>
type McpResourceReadResultPreloadMatchesContract = AssertAssignable<McpResourceReadResultContract, McpResourceReadResultPreload>
type McpResourceReadResultContractMatchesPreload = AssertAssignable<McpResourceReadResultPreload, McpResourceReadResultContract>
type ShortcutUserConfigPreloadMatchesContract = AssertAssignable<ShortcutUserConfigContract, ShortcutUserConfigPreload>
type ShortcutUserConfigContractMatchesPreload = AssertAssignable<ShortcutUserConfigPreload, ShortcutUserConfigContract>
type UserRuleConfigPreloadMatchesContract = AssertAssignable<UserRuleConfigContract, UserRuleConfigPreload>
type UserRuleConfigContractMatchesPreload = AssertAssignable<UserRuleConfigPreload, UserRuleConfigContract>
type SettingsPreferencesSnapshotPreloadMatchesContract = AssertAssignable<SettingsPreferencesSnapshotContract, SettingsPreferencesSnapshotPreload>
type SettingsPreferencesSnapshotContractMatchesPreload = AssertAssignable<SettingsPreferencesSnapshotPreload, SettingsPreferencesSnapshotContract>
type SettingsPreferencesResultPreloadMatchesContract = AssertAssignable<SettingsPreferencesResultContract, SettingsPreferencesResultPreload>
type SettingsPreferencesResultContractMatchesPreload = AssertAssignable<SettingsPreferencesResultPreload, SettingsPreferencesResultContract>
type SettingsRuleSaveInputPreloadMatchesContract = AssertAssignable<SettingsRuleSaveInputContract, SettingsRuleSaveInputPreload>
type SettingsRuleSaveInputContractMatchesPreload = AssertAssignable<SettingsRuleSaveInputPreload, SettingsRuleSaveInputContract>
type SettingsRuleDeleteResultPreloadMatchesContract = AssertAssignable<SettingsRuleDeleteResultContract, SettingsRuleDeleteResultPreload>
type SettingsRuleDeleteResultContractMatchesPreload = AssertAssignable<SettingsRuleDeleteResultPreload, SettingsRuleDeleteResultContract>
type SettingsPreferencesMutationPreloadMatchesContract = AssertAssignable<
  SettingsPreferencesMutationResultContract,
  SettingsPreferencesMutationResultPreload
>
type SettingsPreferencesMutationContractMatchesPreload = AssertAssignable<
  SettingsPreferencesMutationResultPreload,
  SettingsPreferencesMutationResultContract
>
type SettingsShortcutSaveInputPreloadMatchesContract = AssertAssignable<SettingsShortcutSaveInputContract, SettingsShortcutSaveInputPreload>
type SettingsShortcutSaveInputContractMatchesPreload = AssertAssignable<SettingsShortcutSaveInputPreload, SettingsShortcutSaveInputContract>
type SkillUserConfigPreloadMatchesContract = AssertAssignable<SkillUserConfigContract, SkillUserConfigPreload>
type SkillUserConfigContractMatchesPreload = AssertAssignable<SkillUserConfigPreload, SkillUserConfigContract>
type SkillMetadataConfigPreloadMatchesContract = AssertAssignable<SkillMetadataConfigContract, SkillMetadataConfigPreload>
type SkillMetadataConfigContractMatchesPreload = AssertAssignable<SkillMetadataConfigPreload, SkillMetadataConfigContract>
type SkillContentResultPreloadMatchesContract = AssertAssignable<SkillContentResultContract, SkillContentResultPreload>
type SkillContentResultContractMatchesPreload = AssertAssignable<SkillContentResultPreload, SkillContentResultContract>
type SkillWriteResultPreloadMatchesContract = AssertAssignable<SkillWriteResultContract, SkillWriteResultPreload>
type SkillWriteResultContractMatchesPreload = AssertAssignable<SkillWriteResultPreload, SkillWriteResultContract>
type SkillEnabledResultPreloadMatchesContract = AssertAssignable<SkillEnabledResultContract, SkillEnabledResultPreload>
type SkillEnabledResultContractMatchesPreload = AssertAssignable<SkillEnabledResultPreload, SkillEnabledResultContract>
type SkillDeleteResultPreloadMatchesContract = AssertAssignable<SkillDeleteResultContract, SkillDeleteResultPreload>
type SkillDeleteResultContractMatchesPreload = AssertAssignable<SkillDeleteResultPreload, SkillDeleteResultContract>
type SkillImportErrorCodePreloadMatchesContract = AssertAssignable<SkillImportErrorCodeContract, SkillImportErrorCodePreload>
type SkillImportErrorCodeContractMatchesPreload = AssertAssignable<SkillImportErrorCodePreload, SkillImportErrorCodeContract>
type SkillImportResultPreloadMatchesContract = AssertAssignable<SkillImportResultContract, SkillImportResultPreload>
type SkillImportResultContractMatchesPreload = AssertAssignable<SkillImportResultPreload, SkillImportResultContract>
type SkillExportResultPreloadMatchesContract = AssertAssignable<SkillExportResultContract, SkillExportResultPreload>
type SkillExportResultContractMatchesPreload = AssertAssignable<SkillExportResultPreload, SkillExportResultContract>
type KnowledgeNodeConfigPreloadMatchesContract = AssertAssignable<KnowledgeBaseNodeConfigContract, KnowledgeBaseNodeConfigPreload>
type KnowledgeNodeConfigContractMatchesPreload = AssertAssignable<KnowledgeBaseNodeConfigPreload, KnowledgeBaseNodeConfigContract>
type KnowledgeNodeTypePreloadMatchesContract = AssertAssignable<KnowledgeNodeTypeContract, KnowledgeNodeTypePreload>
type KnowledgeNodeTypeContractMatchesPreload = AssertAssignable<KnowledgeNodeTypePreload, KnowledgeNodeTypeContract>
type KnowledgeNodePreloadMatchesContract = AssertAssignable<KnowledgeNodeContract, KnowledgeNodePreload>
type KnowledgeNodeContractMatchesPreload = AssertAssignable<KnowledgeNodePreload, KnowledgeNodeContract>
type KnowledgeUserConfigPreloadMatchesContract = AssertAssignable<KnowledgeBaseUserConfigContract, KnowledgeBaseUserConfigPreload>
type KnowledgeUserConfigContractMatchesPreload = AssertAssignable<KnowledgeBaseUserConfigPreload, KnowledgeBaseUserConfigContract>
type KnowledgeEntryPreloadMatchesContract = AssertAssignable<KnowledgeBaseEntryContract, KnowledgeBaseEntryPreload>
type KnowledgeEntryContractMatchesPreload = AssertAssignable<KnowledgeBaseEntryPreload, KnowledgeBaseEntryContract>
type KnowledgeReadResultPreloadMatchesContract = AssertAssignable<KnowledgeBaseReadResultContract, KnowledgeBaseReadResultPreload>
type KnowledgeReadResultContractMatchesPreload = AssertAssignable<KnowledgeBaseReadResultPreload, KnowledgeBaseReadResultContract>
type KnowledgeWriteResultPreloadMatchesContract = AssertAssignable<KnowledgeBaseWriteResultContract, KnowledgeBaseWriteResultPreload>
type KnowledgeWriteResultContractMatchesPreload = AssertAssignable<KnowledgeBaseWriteResultPreload, KnowledgeBaseWriteResultContract>
type KnowledgeCreateResultPreloadMatchesContract = AssertAssignable<KnowledgeBaseCreateResultContract, KnowledgeBaseCreateResultPreload>
type KnowledgeCreateResultContractMatchesPreload = AssertAssignable<KnowledgeBaseCreateResultPreload, KnowledgeBaseCreateResultContract>
type KnowledgeDeleteResultPreloadMatchesContract = AssertAssignable<KnowledgeBaseDeleteResultContract, KnowledgeBaseDeleteResultPreload>
type KnowledgeDeleteResultContractMatchesPreload = AssertAssignable<KnowledgeBaseDeleteResultPreload, KnowledgeBaseDeleteResultContract>
type KnowledgeImportResultPreloadMatchesContract = AssertAssignable<KnowledgeBaseImportResultContract, KnowledgeBaseImportResultPreload>
type KnowledgeImportResultContractMatchesPreload = AssertAssignable<KnowledgeBaseImportResultPreload, KnowledgeBaseImportResultContract>
type KnowledgePastedImageResultPreloadMatchesContract = AssertAssignable<KnowledgeBasePastedImageResultContract, KnowledgeBasePastedImageResultPreload>
type KnowledgePastedImageResultContractMatchesPreload = AssertAssignable<KnowledgeBasePastedImageResultPreload, KnowledgeBasePastedImageResultContract>
type KnowledgeTransferProgressPreloadMatchesContract = AssertAssignable<KnowledgeBaseTransferProgressContract, KnowledgeBaseTransferProgressPreload>
type KnowledgeTransferProgressContractMatchesPreload = AssertAssignable<KnowledgeBaseTransferProgressPreload, KnowledgeBaseTransferProgressContract>
type KnowledgeSearchResultPreloadMatchesContract = AssertAssignable<KnowledgeBaseSearchResultContract, KnowledgeBaseSearchResultPreload>
type KnowledgeSearchResultContractMatchesPreload = AssertAssignable<KnowledgeBaseSearchResultPreload, KnowledgeBaseSearchResultContract>
type KnowledgeSearchStatusPreloadMatchesContract = AssertAssignable<KnowledgeBaseSearchStatusContract, KnowledgeBaseSearchStatusPreload>
type KnowledgeSearchStatusContractMatchesPreload = AssertAssignable<KnowledgeBaseSearchStatusPreload, KnowledgeBaseSearchStatusContract>
type TerminalUserConfigPreloadMatchesContract = AssertAssignable<TerminalUserConfigContract, TerminalUserConfigPreload>
type TerminalUserConfigContractMatchesPreload = AssertAssignable<TerminalUserConfigPreload, TerminalUserConfigContract>
type WorkspaceUserConfigPreloadMatchesContract = AssertAssignable<WorkspaceUserConfigContract, WorkspaceUserConfigPreload>
type WorkspaceUserConfigContractMatchesPreload = AssertAssignable<WorkspaceUserConfigPreload, WorkspaceUserConfigContract>
type EditorUserConfigPreloadMatchesContract = AssertAssignable<EditorUserConfigContract, EditorUserConfigPreload>
type EditorUserConfigContractMatchesPreload = AssertAssignable<EditorUserConfigPreload, EditorUserConfigContract>
type SshProxyConfigPreloadMatchesContract = AssertAssignable<SshProxyConfigContract, SshProxyConfigPreload>
type SshProxyConfigContractMatchesPreload = AssertAssignable<SshProxyConfigPreload, SshProxyConfigContract>
type SshAgentKeychainPreloadMatchesContract = AssertAssignable<SshAgentKeychainOptionContract, SshAgentKeychainOptionPreload>
type SshAgentKeychainContractMatchesPreload = AssertAssignable<SshAgentKeychainOptionPreload, SshAgentKeychainOptionContract>
type KeywordHighlightUserConfigPreloadMatchesContract = AssertAssignable<KeywordHighlightUserConfigContract, KeywordHighlightUserConfigPreload>
type KeywordHighlightUserConfigContractMatchesPreload = AssertAssignable<KeywordHighlightUserConfigPreload, KeywordHighlightUserConfigContract>
type SecurityUserConfigPreloadMatchesContract = AssertAssignable<SecurityUserConfigContract, SecurityUserConfigPreload>
type SecurityUserConfigContractMatchesPreload = AssertAssignable<SecurityUserConfigPreload, SecurityUserConfigContract>
type PrivacyRuntimeApplyResultPreloadMatchesContract = AssertAssignable<PrivacyRuntimeApplyResultContract, PrivacyRuntimeApplyResultPreload>
type PrivacyRuntimeApplyResultContractMatchesPreload = AssertAssignable<PrivacyRuntimeApplyResultPreload, PrivacyRuntimeApplyResultContract>
type AiPreferencesUserConfigPreloadMatchesContract = AssertAssignable<AiPreferencesUserConfigContract, AiPreferencesUserConfigPreload>
type AiPreferencesUserConfigContractMatchesPreload = AssertAssignable<AiPreferencesUserConfigPreload, AiPreferencesUserConfigContract>
type KnowledgeSearchRuntimeApplyResultPreloadMatchesContract = AssertAssignable<
  KnowledgeSearchRuntimeApplyResultContract,
  KnowledgeSearchRuntimeApplyResultPreload
>
type KnowledgeSearchRuntimeApplyResultContractMatchesPreload = AssertAssignable<
  KnowledgeSearchRuntimeApplyResultPreload,
  KnowledgeSearchRuntimeApplyResultContract
>
type ModelSettingsUserConfigPreloadMatchesContract = AssertAssignable<ModelSettingsUserConfigContract, ModelSettingsUserConfigPreload>
type ModelSettingsUserConfigContractMatchesPreload = AssertAssignable<ModelSettingsUserConfigPreload, ModelSettingsUserConfigContract>
type AiModelCatalogPreloadMatchesContract = AssertAssignable<AiModelCatalogContract, AiModelCatalogPreload>
type AiModelCatalogContractMatchesPreload = AssertAssignable<AiModelCatalogPreload, AiModelCatalogContract>
type ModelProviderCheckInputPreloadMatchesContract = AssertAssignable<ModelProviderCheckInputContract, ModelProviderCheckInputPreload>
type ModelProviderCheckInputContractMatchesPreload = AssertAssignable<ModelProviderCheckInputPreload, ModelProviderCheckInputContract>
type AppUpdateCheckResultPreloadMatchesContract = AssertAssignable<AppUpdateCheckResultContract, AppUpdateCheckResultPreload>
type AppUpdateCheckResultContractMatchesPreload = AssertAssignable<AppUpdateCheckResultPreload, AppUpdateCheckResultContract>
type AppUpdateDownloadResultPreloadMatchesContract = AssertAssignable<AppUpdateDownloadResultContract, AppUpdateDownloadResultPreload>
type AppUpdateDownloadResultContractMatchesPreload = AssertAssignable<AppUpdateDownloadResultPreload, AppUpdateDownloadResultContract>
type OpenSettingsDocumentationInputPreloadMatchesContract = AssertAssignable<OpenSettingsDocumentationInputContract, OpenSettingsDocumentationInputPreload>
type OpenSettingsDocumentationInputContractMatchesPreload = AssertAssignable<OpenSettingsDocumentationInputPreload, OpenSettingsDocumentationInputContract>
type CustomBackgroundSaveResultPreloadMatchesContract = AssertAssignable<CustomBackgroundSaveResultContract, CustomBackgroundSaveResultPreload>
type CustomBackgroundSaveResultContractMatchesPreload = AssertAssignable<CustomBackgroundSaveResultPreload, CustomBackgroundSaveResultContract>
type OpenDialogOptionsPreloadMatchesContract = AssertAssignable<OpenDialogOptionsContract, OpenDialogOptionsPreload>
type OpenDialogOptionsContractMatchesPreload = AssertAssignable<OpenDialogOptionsPreload, OpenDialogOptionsContract>
type OpenDialogResultPreloadMatchesContract = AssertAssignable<OpenDialogResultContract, OpenDialogResultPreload>
type OpenDialogResultContractMatchesPreload = AssertAssignable<OpenDialogResultPreload, OpenDialogResultContract>
type SaveDialogOptionsPreloadMatchesContract = AssertAssignable<SaveDialogOptionsContract, SaveDialogOptionsPreload>
type SaveDialogOptionsContractMatchesPreload = AssertAssignable<SaveDialogOptionsPreload, SaveDialogOptionsContract>
type SaveDialogResultPreloadMatchesContract = AssertAssignable<SaveDialogResultContract, SaveDialogResultPreload>
type SaveDialogResultContractMatchesPreload = AssertAssignable<SaveDialogResultPreload, SaveDialogResultContract>
type LocalFileReadResultPreloadMatchesContract = AssertAssignable<LocalFileReadResultContract, LocalFileReadResultPreload>
type LocalFileReadResultContractMatchesPreload = AssertAssignable<LocalFileReadResultPreload, LocalFileReadResultContract>
type LocalFileWriteResultPreloadMatchesContract = AssertAssignable<LocalFileWriteResultContract, LocalFileWriteResultPreload>
type LocalFileWriteResultContractMatchesPreload = AssertAssignable<LocalFileWriteResultPreload, LocalFileWriteResultContract>
type ChatAttachmentStageResultPreloadMatchesContract = AssertAssignable<ChatAttachmentStageResultContract, ChatAttachmentStageResultPreload>
type ChatAttachmentStageResultContractMatchesPreload = AssertAssignable<ChatAttachmentStageResultPreload, ChatAttachmentStageResultContract>
type ChatImageAttachmentValidateResultPreloadMatchesContract = AssertAssignable<ChatImageAttachmentValidateResultContract, ChatImageAttachmentValidateResultPreload>
type ChatImageAttachmentValidateResultContractMatchesPreload = AssertAssignable<ChatImageAttachmentValidateResultPreload, ChatImageAttachmentValidateResultContract>
type ChatImageAttachmentPrepareResultPreloadMatchesContract = AssertAssignable<ChatImageAttachmentPrepareResultContract, ChatImageAttachmentPrepareResultPreload>
type ChatImageAttachmentPrepareResultContractMatchesPreload = AssertAssignable<ChatImageAttachmentPrepareResultPreload, ChatImageAttachmentPrepareResultContract>
type ControlWorkspaceSnapshotPreloadMatchesContract = AssertAssignable<ControlWorkspaceSnapshotContract, ControlWorkspaceSnapshotPreload>
type ControlWorkspaceSnapshotContractMatchesPreload = AssertAssignable<ControlWorkspaceSnapshotPreload, ControlWorkspaceSnapshotContract>
type ControlSessionSnapshotPreloadMatchesContract = AssertAssignable<ControlSessionSnapshotContract, ControlSessionSnapshotPreload>
type ControlSessionSnapshotContractMatchesPreload = AssertAssignable<ControlSessionSnapshotPreload, ControlSessionSnapshotContract>
type ControlNotificationRecordPreloadMatchesContract = AssertAssignable<ControlNotificationRecordContract, ControlNotificationRecordPreload>
type ControlNotificationRecordContractMatchesPreload = AssertAssignable<ControlNotificationRecordPreload, ControlNotificationRecordContract>
type ControlRequestPreloadMatchesContract = AssertAssignable<ControlRequestContract, ControlRequestPreload>
type ControlRequestContractMatchesPreload = AssertAssignable<ControlRequestPreload, ControlRequestContract>
type ControlResponsePreloadMatchesContract = AssertAssignable<ControlResponseContract, ControlResponsePreload>
type ControlResponseContractMatchesPreload = AssertAssignable<ControlResponsePreload, ControlResponseContract>
type ControlAgentTeamLaunchResultPreloadMatchesContract = AssertAssignable<ControlAgentTeamLaunchResultContract, ControlAgentTeamLaunchResultPreload>
type ControlAgentTeamLaunchResultContractMatchesPreload = AssertAssignable<ControlAgentTeamLaunchResultPreload, ControlAgentTeamLaunchResultContract>
type ExternalCodexMcpConnectionPreloadMatchesContract = AssertAssignable<ExternalCodexMcpConnectionContract, ExternalCodexMcpConnectionPreload>
type ExternalCodexMcpConnectionContractMatchesPreload = AssertAssignable<ExternalCodexMcpConnectionPreload, ExternalCodexMcpConnectionContract>
type ExternalCodexMcpResponsePreloadMatchesContract = AssertAssignable<ExternalCodexMcpResponseContract, ExternalCodexMcpResponsePreload>
type ExternalCodexMcpResponseContractMatchesPreload = AssertAssignable<ExternalCodexMcpResponsePreload, ExternalCodexMcpResponseContract>
type AiContextCatalogPreloadMatchesContract = AssertAssignable<AiContextCatalogResultContract, AiContextCatalogResultPreload>
type AiContextCatalogContractMatchesPreload = AssertAssignable<AiContextCatalogResultPreload, AiContextCatalogResultContract>
type AiCommandCatalogPreloadMatchesContract = AssertAssignable<AiCommandCatalogResultContract, AiCommandCatalogResultPreload>
type AiCommandCatalogContractMatchesPreload = AssertAssignable<AiCommandCatalogResultPreload, AiCommandCatalogResultContract>
type AiContentPartPreloadMatchesContract = AssertAssignable<AiContentPartContract, AiContentPartPreload>
type AiContentPartContractMatchesPreload = AssertAssignable<AiContentPartPreload, AiContentPartContract>
type AiChatHistoryMessagePreloadMatchesContract = AssertAssignable<AiChatHistoryMessageContract, AiChatHistoryMessagePreload>
type AiChatHistoryMessageContractMatchesPreload = AssertAssignable<AiChatHistoryMessagePreload, AiChatHistoryMessageContract>
type AiChatConversationMutationPreloadMatchesContract = AssertAssignable<AiChatConversationMutationResultContract, AiChatConversationMutationResultPreload>
type AiChatConversationMutationContractMatchesPreload = AssertAssignable<AiChatConversationMutationResultPreload, AiChatConversationMutationResultContract>
type AiMcpToolCallActionPreloadMatchesContract = AssertAssignable<AiMcpToolCallActionResultContract, AiMcpToolCallActionResultPreload>
type AiMcpToolCallActionContractMatchesPreload = AssertAssignable<AiMcpToolCallActionResultPreload, AiMcpToolCallActionResultContract>
type AiTodoSnapshotPreloadMatchesContract = AssertAssignable<AiTodoSnapshotResultContract, AiTodoSnapshotResultPreload>
type AiTodoSnapshotContractMatchesPreload = AssertAssignable<AiTodoSnapshotResultPreload, AiTodoSnapshotResultContract>
type AiChatExchangeRequestInputPreloadMatchesContract = AssertAssignable<AiChatExchangeRequestInputContract, AiChatExchangeRequestInputPreload>
type AiChatExchangeRequestInputContractMatchesPreload = AssertAssignable<AiChatExchangeRequestInputPreload, AiChatExchangeRequestInputContract>
type AiChatExchangeRequestPreloadMatchesContract = AssertAssignable<AiChatExchangeRequestResultContract, AiChatExchangeRequestResultPreload>
type AiChatExchangeRequestContractMatchesPreload = AssertAssignable<AiChatExchangeRequestResultPreload, AiChatExchangeRequestResultContract>
type AiChatResponsePreloadMatchesContract = AssertAssignable<AiChatResponseResultContract, AiChatResponseResultPreload>
type AiChatResponseContractMatchesPreload = AssertAssignable<AiChatResponseResultPreload, AiChatResponseResultContract>
type AiChatCancelPreloadMatchesContract = AssertAssignable<AiChatCancelResultContract, AiChatCancelResultPreload>
type AiChatCancelContractMatchesPreload = AssertAssignable<AiChatCancelResultPreload, AiChatCancelResultContract>
type DatabaseWorkspaceCatalogPreloadMatchesContract = AssertAssignable<DatabaseWorkspaceCatalogContract, DatabaseWorkspaceCatalogPreload>
type DatabaseWorkspaceCatalogContractMatchesPreload = AssertAssignable<DatabaseWorkspaceCatalogPreload, DatabaseWorkspaceCatalogContract>
type DatabaseConnectionTestInputPreloadMatchesContract = AssertAssignable<DatabaseConnectionTestInputContract, DatabaseConnectionTestInputPreload>
type DatabaseConnectionTestInputContractMatchesPreload = AssertAssignable<DatabaseConnectionTestInputPreload, DatabaseConnectionTestInputContract>
type DatabaseConnectionTestPreloadMatchesContract = AssertAssignable<DatabaseConnectionTestResultContract, DatabaseConnectionTestResultPreload>
type DatabaseConnectionTestContractMatchesPreload = AssertAssignable<DatabaseConnectionTestResultPreload, DatabaseConnectionTestResultContract>
type DatabaseConnectionSaveInputPreloadMatchesContract = AssertAssignable<DatabaseConnectionSaveInputContract, DatabaseConnectionSaveInputPreload>
type DatabaseConnectionSaveInputContractMatchesPreload = AssertAssignable<DatabaseConnectionSaveInputPreload, DatabaseConnectionSaveInputContract>
type DatabaseSqlExecutePreloadMatchesContract = AssertAssignable<DatabaseSqlExecuteResultContract, DatabaseSqlExecuteResultPreload>
type DatabaseSqlExecuteContractMatchesPreload = AssertAssignable<DatabaseSqlExecuteResultPreload, DatabaseSqlExecuteResultContract>
type DatabaseTableQueryInputPreloadMatchesContract = AssertAssignable<DatabaseTableQueryInputContract, DatabaseTableQueryInputPreload>
type DatabaseTableQueryInputContractMatchesPreload = AssertAssignable<DatabaseTableQueryInputPreload, DatabaseTableQueryInputContract>
type DatabaseTableMutationPlanPreloadMatchesContract = AssertAssignable<DatabaseTableMutationPlanResultContract, DatabaseTableMutationPlanResultPreload>
type DatabaseTableMutationPlanContractMatchesPreload = AssertAssignable<DatabaseTableMutationPlanResultPreload, DatabaseTableMutationPlanResultContract>
type DatabaseExportPreloadMatchesContract = AssertAssignable<DatabaseExportResultContract, DatabaseExportResultPreload>
type DatabaseExportContractMatchesPreload = AssertAssignable<DatabaseExportResultPreload, DatabaseExportResultContract>
type DatabasePageCommentKeyPreloadMatchesContract = AssertAssignable<DatabasePageCommentKeyContract, DatabasePageCommentKeyPreload>
type DatabasePageCommentKeyContractMatchesPreload = AssertAssignable<DatabasePageCommentKeyPreload, DatabasePageCommentKeyContract>
type DatabaseAiPaneStatePreloadMatchesContract = AssertAssignable<DatabaseAiPaneStateSnapshotContract, DatabaseAiPaneStateSnapshotPreload>
type DatabaseAiPaneStateContractMatchesPreload = AssertAssignable<DatabaseAiPaneStateSnapshotPreload, DatabaseAiPaneStateSnapshotContract>
type DatabaseAiPaneResponsePreloadMatchesContract = AssertAssignable<DatabaseAiPaneResponseResultContract, DatabaseAiPaneResponseResultPreload>
type DatabaseAiPaneResponseContractMatchesPreload = AssertAssignable<DatabaseAiPaneResponseResultPreload, DatabaseAiPaneResponseResultContract>
type DatabaseAiDrawerResponseInputPreloadMatchesContract = AssertAssignable<DatabaseAiDrawerResponseInputContract, DatabaseAiDrawerResponseInputPreload>
type DatabaseAiDrawerResponseInputContractMatchesPreload = AssertAssignable<DatabaseAiDrawerResponseInputPreload, DatabaseAiDrawerResponseInputContract>
type DatabaseAiDrawerResponsePreloadMatchesContract = AssertAssignable<DatabaseAiDrawerResponseResultContract, DatabaseAiDrawerResponseResultPreload>
type DatabaseAiDrawerResponseContractMatchesPreload = AssertAssignable<DatabaseAiDrawerResponseResultPreload, DatabaseAiDrawerResponseResultContract>
type DatabaseSqlErrorDiagnosisInputPreloadMatchesContract = AssertAssignable<DatabaseSqlErrorDiagnosisInputContract, DatabaseSqlErrorDiagnosisInputPreload>
type DatabaseSqlErrorDiagnosisInputContractMatchesPreload = AssertAssignable<DatabaseSqlErrorDiagnosisInputPreload, DatabaseSqlErrorDiagnosisInputContract>

describe('shared contract compatibility exports', () => {
  it('keeps Codex session contracts compatible through the preload export', () => {
    const checks: [
      CodexCreateOptionsPreloadMatchesContract,
      CodexCreateOptionsContractMatchesPreload,
      CodexLifecyclePreloadMatchesContract,
      CodexLifecycleContractMatchesPreload,
      CodexTargetUpdatePreloadMatchesContract,
      CodexTargetUpdateContractMatchesPreload
    ] = [true, true, true, true, true, true]

    expect(checks).toEqual([true, true, true, true, true, true])
  })

  it('keeps terminal session contracts compatible through the preload export', () => {
    const checks: [
      TerminalCreateOptionsPreloadMatchesContract,
      TerminalCreateOptionsContractMatchesPreload,
      TerminalLifecyclePreloadMatchesContract,
      TerminalLifecycleContractMatchesPreload,
      TerminalKeyboardInteractivePreloadMatchesContract,
      TerminalKeyboardInteractiveContractMatchesPreload,
      TerminalWriteResultPreloadMatchesContract,
      TerminalWriteResultContractMatchesPreload
    ] = [true, true, true, true, true, true, true, true]

    expect(checks).toEqual([true, true, true, true, true, true, true, true])
  })

  it('keeps terminal tools contracts compatible through the preload export', () => {
    const checks: [
      TerminalCommandSuggestionPreloadMatchesContract,
      TerminalCommandSuggestionContractMatchesPreload,
      TerminalCommandSuggestionContextPreloadMatchesContract,
      TerminalCommandSuggestionContextContractMatchesPreload,
      TerminalCommandGenerationInputPreloadMatchesContract,
      TerminalCommandGenerationInputContractMatchesPreload,
      TerminalCommandGenerationRecordPreloadMatchesContract,
      TerminalCommandGenerationRecordContractMatchesPreload,
      TerminalCommandGenerationResultPreloadMatchesContract,
      TerminalCommandGenerationResultContractMatchesPreload
    ] = [true, true, true, true, true, true, true, true, true, true]

    expect(checks).toEqual([true, true, true, true, true, true, true, true, true, true])
  })

  it('keeps asset contracts compatible through the preload export', () => {
    const checks: [
      AssetInputPreloadMatchesContract,
      AssetInputContractMatchesPreload,
      AssetSnapshotPreloadMatchesContract,
      AssetSnapshotContractMatchesPreload,
      AssetImportPreviewPreloadMatchesContract,
      AssetImportPreviewContractMatchesPreload,
      SshTunnelMutationPreloadMatchesContract,
      SshTunnelMutationContractMatchesPreload
    ] = [true, true, true, true, true, true, true, true]

    expect(checks).toEqual([true, true, true, true, true, true, true, true])
  })

  it('keeps managed AI and agent hook contracts compatible through the preload export', () => {
    const checks: [
      AiAgentSessionEventPreloadMatchesContract,
      AiAgentSessionEventContractMatchesPreload,
      ManagedAiSessionMutationPreloadMatchesContract,
      ManagedAiSessionMutationContractMatchesPreload,
      AgentHibernationConfigPreloadMatchesContract,
      AgentHibernationConfigContractMatchesPreload,
      ManagedAiNotificationMutationPreloadMatchesContract,
      ManagedAiNotificationMutationContractMatchesPreload,
      AgentHookStatusPreloadMatchesContract,
      AgentHookStatusContractMatchesPreload,
      AgentHookOperationPreloadMatchesContract,
      AgentHookOperationContractMatchesPreload
    ] = [true, true, true, true, true, true, true, true, true, true, true, true]

    expect(checks).toEqual([true, true, true, true, true, true, true, true, true, true, true, true])
  })

  it('keeps ZMODEM contracts compatible through the preload export', () => {
    const checks: [
      ZmodemUploadPickPreloadMatchesContract,
      ZmodemUploadPickContractMatchesPreload,
      ZmodemStreamOpenPreloadMatchesContract,
      ZmodemStreamOpenContractMatchesPreload
    ] = [true, true, true, true]

    expect(checks).toEqual([true, true, true, true])
  })

  it('keeps Files contracts compatible through the preload export', () => {
    const checks: [
      FileSessionInfoPreloadMatchesContract,
      FileSessionInfoContractMatchesPreload,
      FileSessionCatalogPreloadMatchesContract,
      FileSessionCatalogContractMatchesPreload,
      FileListEntryPreloadMatchesContract,
      FileListEntryContractMatchesPreload,
      FileTransferOperationPreloadMatchesContract,
      FileTransferOperationContractMatchesPreload
    ] = [true, true, true, true, true, true, true, true]

    expect(checks).toEqual([true, true, true, true, true, true, true, true])
  })

  it('keeps User Account contracts compatible through the preload export', () => {
    const checks: [
      UserAccountResultPreloadMatchesContract,
      UserAccountResultContractMatchesPreload,
      UserLoginInputPreloadMatchesContract,
      UserLoginInputContractMatchesPreload,
      UserMutationPreloadMatchesContract,
      UserMutationContractMatchesPreload,
      TrustedDeviceRevokePreloadMatchesContract,
      TrustedDeviceRevokeContractMatchesPreload
    ] = [true, true, true, true, true, true, true, true]

    expect(checks).toEqual([true, true, true, true, true, true, true, true])
  })

  it('keeps Extensions contracts compatible through the preload export', () => {
    const checks: [
      ExtensionRuntimePreloadMatchesContract,
      ExtensionRuntimeContractMatchesPreload,
      ExtensionOperationPreloadMatchesContract,
      ExtensionOperationContractMatchesPreload,
      ExtensionProgressPreloadMatchesContract,
      ExtensionProgressContractMatchesPreload,
      ExtensionDownloadPreloadMatchesContract,
      ExtensionDownloadContractMatchesPreload,
      ExtensionUserConfigPreloadMatchesContract,
      ExtensionUserConfigContractMatchesPreload
    ] = [true, true, true, true, true, true, true, true, true, true]

    expect(checks).toEqual([true, true, true, true, true, true, true, true, true, true])
  })

  it('keeps Quick Commands contracts compatible through the preload export', () => {
    const checks: [
      QuickCommandsSnapshotPreloadMatchesContract,
      QuickCommandsSnapshotContractMatchesPreload,
      QuickCommandSnippetSavePreloadMatchesContract,
      QuickCommandSnippetSaveContractMatchesPreload,
      QuickCommandSnippetMutationPreloadMatchesContract,
      QuickCommandSnippetMutationContractMatchesPreload,
      QuickCommandScriptPlanPreloadMatchesContract,
      QuickCommandScriptPlanContractMatchesPreload
    ] = [true, true, true, true, true, true, true, true]

    expect(checks).toEqual([true, true, true, true, true, true, true, true])
  })

  it('keeps Alias contracts compatible through the preload export', () => {
    const checks: [
      AliasCommandPreloadMatchesContract,
      AliasCommandContractMatchesPreload,
      AliasSaveInputPreloadMatchesContract,
      AliasSaveInputContractMatchesPreload,
      AliasListResultPreloadMatchesContract,
      AliasListResultContractMatchesPreload,
      AliasMutationPreloadMatchesContract,
      AliasMutationContractMatchesPreload,
      AliasDeleteInputPreloadMatchesContract,
      AliasDeleteInputContractMatchesPreload,
      AliasDeleteResultPreloadMatchesContract,
      AliasDeleteResultContractMatchesPreload
    ] = [true, true, true, true, true, true, true, true, true, true, true, true]

    expect(checks).toEqual([true, true, true, true, true, true, true, true, true, true, true, true])
  })

  it('keeps MCP contracts compatible through the preload export', () => {
    const checks: [
      McpConfigFilePreloadMatchesContract,
      McpConfigFileContractMatchesPreload,
      McpServerPreloadMatchesContract,
      McpServerContractMatchesPreload,
      McpConfigWritePreloadMatchesContract,
      McpConfigWriteContractMatchesPreload,
      McpToolCallInputPreloadMatchesContract,
      McpToolCallInputContractMatchesPreload,
      McpToolCallResultPreloadMatchesContract,
      McpToolCallResultContractMatchesPreload,
      McpResourceReadInputPreloadMatchesContract,
      McpResourceReadInputContractMatchesPreload,
      McpResourceReadResultPreloadMatchesContract,
      McpResourceReadResultContractMatchesPreload
    ] = [true, true, true, true, true, true, true, true, true, true, true, true, true, true]

    expect(checks).toEqual([true, true, true, true, true, true, true, true, true, true, true, true, true, true])
  })

  it('keeps Settings Preferences contracts compatible through the preload export', () => {
    const checks: [
      ShortcutUserConfigPreloadMatchesContract,
      ShortcutUserConfigContractMatchesPreload,
      UserRuleConfigPreloadMatchesContract,
      UserRuleConfigContractMatchesPreload,
      SettingsPreferencesSnapshotPreloadMatchesContract,
      SettingsPreferencesSnapshotContractMatchesPreload,
      SettingsPreferencesResultPreloadMatchesContract,
      SettingsPreferencesResultContractMatchesPreload,
      SettingsRuleSaveInputPreloadMatchesContract,
      SettingsRuleSaveInputContractMatchesPreload,
      SettingsRuleDeleteResultPreloadMatchesContract,
      SettingsRuleDeleteResultContractMatchesPreload,
      SettingsPreferencesMutationPreloadMatchesContract,
      SettingsPreferencesMutationContractMatchesPreload,
      SettingsShortcutSaveInputPreloadMatchesContract,
      SettingsShortcutSaveInputContractMatchesPreload
    ] = [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true]

    expect(checks).toEqual([true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true])
  })

  it('keeps Skills contracts compatible through the preload export', () => {
    const checks: [
      SkillUserConfigPreloadMatchesContract,
      SkillUserConfigContractMatchesPreload,
      SkillMetadataConfigPreloadMatchesContract,
      SkillMetadataConfigContractMatchesPreload,
      SkillContentResultPreloadMatchesContract,
      SkillContentResultContractMatchesPreload,
      SkillWriteResultPreloadMatchesContract,
      SkillWriteResultContractMatchesPreload,
      SkillEnabledResultPreloadMatchesContract,
      SkillEnabledResultContractMatchesPreload,
      SkillDeleteResultPreloadMatchesContract,
      SkillDeleteResultContractMatchesPreload,
      SkillImportErrorCodePreloadMatchesContract,
      SkillImportErrorCodeContractMatchesPreload,
      SkillImportResultPreloadMatchesContract,
      SkillImportResultContractMatchesPreload,
      SkillExportResultPreloadMatchesContract,
      SkillExportResultContractMatchesPreload
    ] = [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true]

    expect(checks).toEqual([true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true])
  })

  it('keeps Knowledge Base contracts compatible through the preload export', () => {
    const checks: [
      KnowledgeNodeConfigPreloadMatchesContract,
      KnowledgeNodeConfigContractMatchesPreload,
      KnowledgeNodeTypePreloadMatchesContract,
      KnowledgeNodeTypeContractMatchesPreload,
      KnowledgeNodePreloadMatchesContract,
      KnowledgeNodeContractMatchesPreload,
      KnowledgeUserConfigPreloadMatchesContract,
      KnowledgeUserConfigContractMatchesPreload,
      KnowledgeEntryPreloadMatchesContract,
      KnowledgeEntryContractMatchesPreload,
      KnowledgeReadResultPreloadMatchesContract,
      KnowledgeReadResultContractMatchesPreload,
      KnowledgeWriteResultPreloadMatchesContract,
      KnowledgeWriteResultContractMatchesPreload,
      KnowledgeCreateResultPreloadMatchesContract,
      KnowledgeCreateResultContractMatchesPreload,
      KnowledgeDeleteResultPreloadMatchesContract,
      KnowledgeDeleteResultContractMatchesPreload,
      KnowledgeImportResultPreloadMatchesContract,
      KnowledgeImportResultContractMatchesPreload,
      KnowledgePastedImageResultPreloadMatchesContract,
      KnowledgePastedImageResultContractMatchesPreload,
      KnowledgeTransferProgressPreloadMatchesContract,
      KnowledgeTransferProgressContractMatchesPreload,
      KnowledgeSearchResultPreloadMatchesContract,
      KnowledgeSearchResultContractMatchesPreload,
      KnowledgeSearchStatusPreloadMatchesContract,
      KnowledgeSearchStatusContractMatchesPreload
    ] = [
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true
    ]

    expect(checks).toEqual([
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true
    ])
  })

  it('keeps App Runtime contracts compatible through the preload export', () => {
    const checks: [
      TerminalUserConfigPreloadMatchesContract,
      TerminalUserConfigContractMatchesPreload,
      WorkspaceUserConfigPreloadMatchesContract,
      WorkspaceUserConfigContractMatchesPreload,
      EditorUserConfigPreloadMatchesContract,
      EditorUserConfigContractMatchesPreload,
      SshProxyConfigPreloadMatchesContract,
      SshProxyConfigContractMatchesPreload,
      SshAgentKeychainPreloadMatchesContract,
      SshAgentKeychainContractMatchesPreload,
      KeywordHighlightUserConfigPreloadMatchesContract,
      KeywordHighlightUserConfigContractMatchesPreload,
      SecurityUserConfigPreloadMatchesContract,
      SecurityUserConfigContractMatchesPreload,
      PrivacyRuntimeApplyResultPreloadMatchesContract,
      PrivacyRuntimeApplyResultContractMatchesPreload,
      AiPreferencesUserConfigPreloadMatchesContract,
      AiPreferencesUserConfigContractMatchesPreload,
      KnowledgeSearchRuntimeApplyResultPreloadMatchesContract,
      KnowledgeSearchRuntimeApplyResultContractMatchesPreload,
      ModelSettingsUserConfigPreloadMatchesContract,
      ModelSettingsUserConfigContractMatchesPreload,
      AiModelCatalogPreloadMatchesContract,
      AiModelCatalogContractMatchesPreload,
      ModelProviderCheckInputPreloadMatchesContract,
      ModelProviderCheckInputContractMatchesPreload,
      AppUpdateCheckResultPreloadMatchesContract,
      AppUpdateCheckResultContractMatchesPreload,
      AppUpdateDownloadResultPreloadMatchesContract,
      AppUpdateDownloadResultContractMatchesPreload,
      OpenSettingsDocumentationInputPreloadMatchesContract,
      OpenSettingsDocumentationInputContractMatchesPreload,
      CustomBackgroundSaveResultPreloadMatchesContract,
      CustomBackgroundSaveResultContractMatchesPreload
    ] = [
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true
    ]

    expect(checks).toEqual([
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true
    ])
  })

  it('keeps Local Files contracts compatible through the preload export', () => {
    const checks: [
      OpenDialogOptionsPreloadMatchesContract,
      OpenDialogOptionsContractMatchesPreload,
      OpenDialogResultPreloadMatchesContract,
      OpenDialogResultContractMatchesPreload,
      SaveDialogOptionsPreloadMatchesContract,
      SaveDialogOptionsContractMatchesPreload,
      SaveDialogResultPreloadMatchesContract,
      SaveDialogResultContractMatchesPreload,
      LocalFileReadResultPreloadMatchesContract,
      LocalFileReadResultContractMatchesPreload,
      LocalFileWriteResultPreloadMatchesContract,
      LocalFileWriteResultContractMatchesPreload,
      ChatAttachmentStageResultPreloadMatchesContract,
      ChatAttachmentStageResultContractMatchesPreload,
      ChatImageAttachmentValidateResultPreloadMatchesContract,
      ChatImageAttachmentValidateResultContractMatchesPreload,
      ChatImageAttachmentPrepareResultPreloadMatchesContract,
      ChatImageAttachmentPrepareResultContractMatchesPreload
    ] = [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true]

    expect(checks).toEqual([true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true])
  })

  it('keeps Control contracts compatible through the preload export', () => {
    const checks: [
      ControlWorkspaceSnapshotPreloadMatchesContract,
      ControlWorkspaceSnapshotContractMatchesPreload,
      ControlSessionSnapshotPreloadMatchesContract,
      ControlSessionSnapshotContractMatchesPreload,
      ControlNotificationRecordPreloadMatchesContract,
      ControlNotificationRecordContractMatchesPreload,
      ControlRequestPreloadMatchesContract,
      ControlRequestContractMatchesPreload,
      ControlResponsePreloadMatchesContract,
      ControlResponseContractMatchesPreload,
      ControlAgentTeamLaunchResultPreloadMatchesContract,
      ControlAgentTeamLaunchResultContractMatchesPreload,
      ExternalCodexMcpConnectionPreloadMatchesContract,
      ExternalCodexMcpConnectionContractMatchesPreload,
      ExternalCodexMcpResponsePreloadMatchesContract,
      ExternalCodexMcpResponseContractMatchesPreload
    ] = [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true]

    expect(checks).toEqual([true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true])
  })

  it('keeps AI Chat contracts compatible through the preload export', () => {
    const checks: [
      AiContextCatalogPreloadMatchesContract,
      AiContextCatalogContractMatchesPreload,
      AiCommandCatalogPreloadMatchesContract,
      AiCommandCatalogContractMatchesPreload,
      AiContentPartPreloadMatchesContract,
      AiContentPartContractMatchesPreload,
      AiChatHistoryMessagePreloadMatchesContract,
      AiChatHistoryMessageContractMatchesPreload,
      AiChatConversationMutationPreloadMatchesContract,
      AiChatConversationMutationContractMatchesPreload,
      AiMcpToolCallActionPreloadMatchesContract,
      AiMcpToolCallActionContractMatchesPreload,
      AiTodoSnapshotPreloadMatchesContract,
      AiTodoSnapshotContractMatchesPreload,
      AiChatExchangeRequestInputPreloadMatchesContract,
      AiChatExchangeRequestInputContractMatchesPreload,
      AiChatExchangeRequestPreloadMatchesContract,
      AiChatExchangeRequestContractMatchesPreload,
      AiChatResponsePreloadMatchesContract,
      AiChatResponseContractMatchesPreload,
      AiChatCancelPreloadMatchesContract,
      AiChatCancelContractMatchesPreload
    ] = [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true]

    expect(checks).toEqual([true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true])
  })

  it('keeps Database contracts compatible through the preload export', () => {
    const checks: [
      DatabaseWorkspaceCatalogPreloadMatchesContract,
      DatabaseWorkspaceCatalogContractMatchesPreload,
      DatabaseConnectionTestInputPreloadMatchesContract,
      DatabaseConnectionTestInputContractMatchesPreload,
      DatabaseConnectionTestPreloadMatchesContract,
      DatabaseConnectionTestContractMatchesPreload,
      DatabaseConnectionSaveInputPreloadMatchesContract,
      DatabaseConnectionSaveInputContractMatchesPreload,
      DatabaseSqlExecutePreloadMatchesContract,
      DatabaseSqlExecuteContractMatchesPreload,
      DatabaseTableQueryInputPreloadMatchesContract,
      DatabaseTableQueryInputContractMatchesPreload,
      DatabaseTableMutationPlanPreloadMatchesContract,
      DatabaseTableMutationPlanContractMatchesPreload,
      DatabaseExportPreloadMatchesContract,
      DatabaseExportContractMatchesPreload,
      DatabasePageCommentKeyPreloadMatchesContract,
      DatabasePageCommentKeyContractMatchesPreload,
      DatabaseAiPaneStatePreloadMatchesContract,
      DatabaseAiPaneStateContractMatchesPreload,
      DatabaseAiPaneResponsePreloadMatchesContract,
      DatabaseAiPaneResponseContractMatchesPreload,
      DatabaseAiDrawerResponseInputPreloadMatchesContract,
      DatabaseAiDrawerResponseInputContractMatchesPreload,
      DatabaseAiDrawerResponsePreloadMatchesContract,
      DatabaseAiDrawerResponseContractMatchesPreload,
      DatabaseSqlErrorDiagnosisInputPreloadMatchesContract,
      DatabaseSqlErrorDiagnosisInputContractMatchesPreload
    ] = [
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true
    ]

    expect(checks).toEqual([
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true
    ])
  })
})
