<template>
  <section
    class="database-workspace"
    data-ui-focus-scope="database"
    data-ui-focus-primary
    tabindex="-1"
    :class="{
      'db-ai-pane-visible': dbAiPaneOpen,
      'db-ai-pane-resizing': dbAiPaneResizing
    }"
    :style="databaseWorkspaceStyle"
  >
    <DatabaseSidebarTree
      ref="databaseSidebarTreeRef"
      :sidebar-collapsed="sidebarCollapsed"
      :keyword="keyword"
      :visible-group-nodes="visibleGroupNodes"
      :selected-node-id="selectedNodeId"
      :editing-group-id="editingGroupId"
      :editing-group-name="editingGroupName"
      :expanded-groups="expandedGroups"
      :expanded-connections="expandedConnections"
      :expanded-catalogs="expandedCatalogs"
      :expanded-schemas="expandedSchemas"
      :expanded-schema-object-folders="expandedSchemaObjectFolders"
      :expanded-tables="expandedTables"
      :connections-by-group="connectionsByGroup"
      :engine-accent="engineAccent"
      @update-sidebar-collapsed="sidebarCollapsed = $event"
      @update-keyword="keyword = $event"
      @clear-search="clearDatabaseSearch"
      @refresh-connected="refreshConnected"
      @toggle-add-menu="toggleAddMenu"
      @select-node="selectNode"
      @open-context-menu="openContextMenu"
      @toggle-group="toggleGroup"
      @update-editing-group-name="editingGroupName = $event"
      @commit-group-rename="commitGroupRename"
      @cancel-group-rename="cancelGroupRename"
      @toggle-connection="toggleConnection"
      @toggle-connection-status="toggleConnectionStatus"
      @toggle-catalog="toggleCatalog"
      @toggle-schema="toggleSchema"
      @toggle-schema-object-folder="toggleSchemaObjectFolder"
      @open-table="openTable"
      @toggle-table="toggleTable"
      @select-column-node="selectColumnNode"
    />

    <DatabaseMainWorkspace
      ref="sqlEditorRef"
      v-model:active-tab-id="activeTabId"
      v-model:overflow-open="overflowOpen"
      v-model:sql-find-query="sqlFindQuery"
      v-model:sql-find-replace="sqlFindReplace"
      v-model:sql-find-case-sensitive="sqlFindCaseSensitive"
      :tabs="tabs"
      :active-tab="activeTab"
      :db-ai-pane-open="dbAiPaneOpen"
      :can-toggle-db-ai-pane="canToggleDbAiPane"
      :database-engines="databaseEngines"
      :active-sql-tab="activeSqlTab"
      :active-sql-can-run="activeSqlCanRun"
      :active-sql-saving="activeSqlSaving"
      :active-sql-save-title="activeSqlSaveTitle"
      :active-sql-has-text="activeSqlHasText"
      :connections="connections"
      :current-sql-catalogs="currentSqlCatalogs"
      :current-sql-schemas="currentSqlSchemas"
      :active-sql-requires-schema="activeSqlRequiresSchema"
      :sql-pane-resizing="sqlPaneResizing"
      :sql-pane-style="sqlPaneStyle"
      :sql-editor-scroll-top="sqlEditorScrollTop"
      :active-sql-editor-lines="activeSqlEditorLines"
      :sql-editor-active-line="sqlEditorActiveLine"
      :sql-editor-active-line-top="sqlEditorActiveLineTop"
      :sql-find-open="sqlFindOpen"
      :sql-find-summary="sqlFindSummary"
      :sql-find-matches="sqlFindMatches"
      :sql-find-replace-open="sqlFindReplaceOpen"
      :active-sql-is-dirty="activeSqlIsDirty"
      :active-sql-save-state-text="activeSqlSaveStateText"
      :active-sql-editor-line-count="activeSqlEditorLineCount"
      :sql-editor-active-column="sqlEditorActiveColumn"
      :sql-editor-selection-size="sqlEditorSelectionSize"
      :sql-pane-min-percent="SQL_PANE_MIN_PERCENT"
      :sql-pane-max-percent="SQL_PANE_MAX_PERCENT"
      :sql-pane-editor-percent="sqlPaneEditorPercent"
      :active-sql-result="activeSqlResult"
      :active-sql-result-view-state="activeSqlResultViewState"
      :filtered-sql-rows="filteredSqlRows"
      :paged-sql-rows="pagedSqlRows"
      :sql-diagnose="sqlDiagnose"
      :active-data-tab="activeDataTab"
      :active-data-edit-summary="activeDataEditSummary"
      :active-data-where-pending="activeDataWherePending"
      :paged-data-rows="pagedDataRows"
      :can-edit-data-tab="canEditDataTab"
      :is-data-tab-dirty="isDataTabDirty"
      :data-edit-disabled-reason="dataEditDisabledReason"
      :is-sql-history-closed="isSqlHistoryClosed"
      @close-tab="closeTab"
      @open-sql-console="openSqlConsole"
      @toggle-db-ai-pane="toggleDbAiPane"
      @toggle-add-menu="toggleAddMenu"
      @focus-database-search="focusDatabaseSearch"
      @open-overview-engine="openOverviewEngine"
      @run-sql="runSql"
      @save-active-sql="saveActiveSql"
      @format-sql="formatSql"
      @open-db-ai-from-toolbar="openDbAiFromToolbar"
      @update-sql-tab-connection="updateSqlTabConnection"
      @update-sql-tab-catalog="updateSqlTabCatalog"
      @update-sql-tab-schema="updateSqlTabSchema"
      @update-active-sql="updateActiveSql"
      @sync-sql-editor-state="syncSqlEditorState"
      @run-sql-from-shortcut="runSqlFromShortcut"
      @open-sql-find="openSqlFind"
      @handle-sql-find-keydown="handleSqlFindKeydown"
      @go-to-sql-find-match="goToSqlFindMatch"
      @toggle-sql-find-replace="toggleSqlFindReplace"
      @close-sql-find="closeSqlFind"
      @replace-current-sql-find-match="replaceCurrentSqlFindMatch"
      @replace-all-sql-find-matches="replaceAllSqlFindMatches"
      @start-sql-pane-resize="startSqlPaneResize"
      @reset-sql-pane-split="resetSqlPaneSplit"
      @update-sql-result-active-tab="updateSqlResultActiveTab"
      @toggle-result-tab-pinned="toggleResultTabPinned"
      @close-result-tab="closeResultTab"
      @open-sql-history-result="openSqlHistoryResult"
      @diagnose-sql-error="diagnoseSqlError"
      @update-sql-result-page="updateSqlResultPage"
      @goto-last-sql-result-page="gotoLastSqlResultPage"
      @update-sql-result-page-size="updateSqlResultPageSize"
      @export-active-sql-result-page="exportActiveSqlResultPage"
      @open-active-sql-result-chart="openActiveSqlResultChart"
      @open-active-sql-result-comment="openActiveSqlResultComment"
      @cycle-sql-sort="cycleSqlSort"
      @apply-sql-filter="applySqlFilter"
      @update-data-page="updateDataPage"
      @goto-last-data-page="gotoLastDataPage"
      @update-data-page-size="updateDataPageSize"
      @refresh-data-total="refreshDataTotal"
      @refresh-data-tab="refreshDataTab"
      @add-data-row="addDataRow"
      @delete-selected-data-row="deleteSelectedDataRow"
      @undo-data-changes="undoDataChanges"
      @save-data-changes="saveDataChanges"
      @export-active-data-page="exportActiveDataPage"
      @open-active-data-chart="openActiveDataChart"
      @open-active-data-comment="openActiveDataComment"
      @update-active-data-where-draft="updateActiveDataWhereDraft"
      @apply-where="applyWhere"
      @copy-data-mutation-preview="copyDataMutationPreview"
      @discard-data-changes="discardDataChanges"
      @cycle-data-sort="cycleDataSort"
      @apply-data-filter="applyDataFilter"
      @set-active-data-selected-row="setActiveDataSelectedRow"
      @update-data-cell="updateDataCell"
      @update-new-data-row-cell="updateNewDataRowCell"
    />

    <DatabaseWorkspaceOverlays
      ref="databaseAiPanelsRef"
      v-model:db-ai-pane-draft="dbAiPaneDraft"
      v-model:connection-url="connectionUrl"
      v-model:password-visible="passwordVisible"
      v-model:create-database-sql="createDatabaseSql"
      v-model:context-submenu="contextSubmenu"
      :db-ai-pane-open="dbAiPaneOpen"
      :db-ai-pane-width="dbAiPaneWidth"
      :db-ai-pane-min-width="DB_AI_PANE_MIN_WIDTH"
      :db-ai-pane-max-width="DB_AI_PANE_MAX_WIDTH"
      :db-ai-pane-context-summary="dbAiPaneContextSummary"
      :db-ai-pane-context-title="dbAiPaneContextTitle"
      :db-ai-pane-context="dbAiPaneContext"
      :connections="connections"
      :db-ai-pane-connection="dbAiPaneConnection"
      :db-ai-pane-catalog-options="dbAiPaneCatalogOptions"
      :db-ai-pane-schema-options="dbAiPaneSchemaOptions"
      :db-ai-pane-requires-schema="dbAiPaneRequiresSchema"
      :db-ai-pane-connection-needs-connect="dbAiPaneConnectionNeedsConnect"
      :db-ai-pane-restore-issues="dbAiPaneRestoreIssues"
      :db-ai-pane-messages="dbAiPaneMessages"
      :db-ai-pane-composer-action="dbAiPaneComposerAction"
      :db-ai-pane-composer-placeholder="dbAiPaneComposerPlaceholder"
      :db-ai-pane-is-streaming="dbAiPaneIsStreaming"
      :db-ai-pane-can-send="dbAiPaneCanSend"
      :active-sql-available="Boolean(activeSqlTab)"
      :active-sql-explain-available="activeSqlHasText"
      :can-run-db-ai-pane-message-sql="canRunDbAiPaneMessageSql"
      :load-older-db-ai-pane-messages="loadOlderDbAiPaneMessages"
      :db-ai-dialect-options="dbAiDialectOptions"
      :format-db-ai-request-time="formatDbAiRequestTime"
      :db-ai-pane-status-label="dbAiPaneStatusLabel"
      :add-menu-open="addMenuOpen"
      :add-menu-position="addMenuPosition"
      :context-menu="contextMenu"
      :database-engines="databaseEngines"
      :group-root-move-disabled="groupRootMoveDisabled"
      :group-move-targets="groupMoveTargets"
      :context-connection-connected="contextConnectionConnected"
      :context-connection-can-create-database="contextConnectionCanCreateDatabase"
      :connection-root-move-disabled="connectionRootMoveDisabled"
      :connection-move-targets="connectionMoveTargets"
      :default-group-id="DEFAULT_GROUP_ID"
      :connection-modal-open="connectionModalOpen"
      :connection-modal-mode="connectionModalMode"
      :connection-draft="connectionDraft"
      :connection-errors="connectionErrors"
      :groups="groups"
      :connection-feedback="connectionFeedback"
      :connection-feedback-kind="connectionFeedbackKind"
      :connection-testing="connectionTesting"
      :connection-saving="connectionSaving"
      :database-proxy-available="databaseProxyAvailable"
      :database-ssh-proxy-options="databaseSshProxyOptions"
      :postgres-ssl-mode-options="postgresSslModeOptions"
      :engine-accent="engineAccent"
      :engine-name="engineName"
      :create-database-modal="createDatabaseModal"
      :create-database-name-error="createDatabaseNameError"
      :create-database-can-submit="createDatabaseCanSubmit"
      :chart-modal="chartModal"
      :comment-modal="commentModal"
      :ddl-modal="ddlModal"
      :danger-confirm="dangerConfirm"
      :operation-confirm="operationConfirm"
      :notice="notice"
      @start-db-ai-pane-resize="startDbAiPaneResize"
      @reset-db-ai-pane-width="resetDbAiPaneWidth"
      @close-db-ai-pane="closeDbAiPane"
      @use-active-db-ai-pane-context="useActiveDbAiPaneContext"
      @update-db-ai-pane-connection="updateDbAiPaneConnection"
      @update-db-ai-pane-catalog="updateDbAiPaneCatalog"
      @update-db-ai-pane-schema="updateDbAiPaneSchema"
      @connect-db-ai-pane-connection="connectDbAiPaneConnection"
      @retry-db-ai-pane-binding="retryDbAiPaneBinding"
      @handle-db-ai-pane-draft-keydown="handleDbAiPaneDraftKeydown"
      @cancel-db-ai-pane-action-mode="cancelDbAiPaneActionMode"
      @send-db-ai-pane-quick-prompt="sendDbAiPaneQuickPrompt"
      @reset-db-ai-pane-conversation="resetDbAiPaneConversation"
      @cancel-db-ai-pane-response="cancelDbAiPaneResponse"
      @send-db-ai-pane-message="() => sendDbAiPaneMessage()"
      @update-db-ai-pane-message-dialect="updateDbAiPaneMessageDialect"
      @copy-db-ai-sql="copyDbAiSql"
      @replace-db-ai-sql-selection="replaceDbAiSqlSelection"
      @insert-db-ai-sql="insertDbAiSql"
      @run-db-ai-readonly="runDbAiReadonly"
      @add-group="addGroup"
      @open-connection-modal-from-engine="openConnectionModalFromEngine"
      @close-context-submenu-soon="closeContextSubmenuSoon"
      @start-group-rename="startGroupRename"
      @copy-context-name="copyContextName"
      @move-group-to="moveGroupTo"
      @request-delete-group="requestDeleteGroup"
      @connect-from-menu="connectFromMenu"
      @open-sql-console="openSqlConsole"
      @open-create-database-modal="openCreateDatabaseModal"
      @edit-connection="editConnection"
      @move-connection-to-group="moveConnectionToGroup"
      @refresh-connection-from-menu="refreshConnectionFromMenu"
      @request-remove-connection="requestRemoveConnection"
      @open-context-table="openContextTable"
      @open-context-sql="openContextSql"
      @open-ddl-modal-from-context="openDdlModalFromContext"
      @copy-select-sql="copySelectSql"
      @copy-table-ddl-from-context="copyTableDdlFromContext"
      @request-dangerous-table-action="requestDangerousTableAction"
      @close-connection-modal="closeConnectionModal"
      @save-connection-draft="saveConnectionDraft"
      @test-connection-draft="testConnectionDraft"
      @pick-sqlite-file="pickSqliteFile"
      @mark-connection-url-auto="markConnectionUrlAuto"
      @open-ssh-proxy-config-from-connection-modal="openSshProxyConfigFromConnectionModal"
      @create-database="createDatabase"
      @close-create-database="closeCreateDatabaseModal"
      @update-create-database-name="updateCreateDatabaseName"
      @close-chart="closeChartModal"
      @close-comment="closeCommentModal"
      @update-comment-draft="updateCommentDraft"
      @save-comment="saveActiveComment"
      @close-ddl="closeDdlModal"
      @copy-ddl="copyDdl"
      @cancel-danger="cancelDangerousTableAction"
      @update-danger-confirm-text="updateDangerConfirmText"
      @confirm-danger="confirmDangerousTableAction"
      @cancel-operation="cancelOperationConfirm"
      @confirm-operation="confirmOperation"
    />
  </section>
</template>

<script setup lang="ts">
import { watch } from 'vue'
import DatabaseMainWorkspace from '@/components/database/DatabaseMainWorkspace.vue'
import DatabaseSidebarTree from '@/components/database/DatabaseSidebarTree.vue'
import DatabaseWorkspaceOverlays from '@/components/database/DatabaseWorkspaceOverlays.vue'
import type { ProductSessionUiRequest } from '@/components/productSessionUiTypes'
import { useI18n } from '@/i18n'
import { useDatabaseWorkspaceRuntime } from '@/services/database/databaseWorkspaceContainerRuntime'
import { useWorkspaceStore } from '@/stores/workspace'

const props = defineProps<{
  productSessionRequest?: ProductSessionUiRequest | null
}>()
const emit = defineEmits<{
  productSessionRequestConsumed: [sequence: number]
}>()
const { t } = useI18n()
const workspace = useWorkspaceStore()

const {
  DB_AI_PANE_MIN_WIDTH,
  DB_AI_PANE_MAX_WIDTH,
  DEFAULT_GROUP_ID,
  databaseEngines,
  groups,
  connections,
  keyword,
  sidebarCollapsed,
  databaseSidebarTreeRef,
  expandedGroups,
  expandedConnections,
  expandedCatalogs,
  expandedSchemas,
  expandedSchemaObjectFolders,
  expandedTables,
  selectedNodeId,
  overflowOpen,
  addMenuOpen,
  addMenuPosition,
  contextMenu,
  contextSubmenu,
  notice,
  editingGroupId,
  editingGroupName,
  tabs,
  activeTabId,
  sqlEditorRef,
  connectionModalOpen,
  connectionModalMode,
  connectionFeedback,
  connectionFeedbackKind,
  connectionErrors,
  passwordVisible,
  connectionTesting,
  connectionSaving,
  postgresSslModeOptions,
  connectionDraft,
  createDatabaseModal,
  ddlModal,
  chartModal,
  commentModal,
  databaseAiPanelsRef,
  dangerConfirm,
  operationConfirm,
  activeTab,
  activeSqlTab,
  activeDataTab,
  activeDataEditSummary,
  activeSqlCanRun,
  currentSqlCatalogs,
  currentSqlSchemas,
  activeSqlRequiresSchema,
  databaseSshProxyOptions,
  databaseProxyAvailable,
  contextConnectionConnected,
  contextConnectionCanCreateDatabase,
  connectionMoveTargets,
  connectionRootMoveDisabled,
  activeSqlResult,
  activeSqlResultViewState,
  activeSqlHasText,
  activeSqlSaving,
  activeSqlIsDirty,
  activeSqlSaveTitle,
  activeSqlSaveStateText,
  SQL_PANE_MIN_PERCENT,
  SQL_PANE_MAX_PERCENT,
  sqlPaneEditorPercent,
  sqlPaneResizing,
  sqlEditorScrollTop,
  sqlEditorActiveLine,
  sqlEditorActiveColumn,
  sqlEditorSelectionSize,
  sqlFindOpen,
  sqlFindReplaceOpen,
  sqlFindQuery,
  sqlFindReplace,
  sqlFindCaseSensitive,
  sqlPaneStyle,
  activeSqlEditorLineCount,
  activeSqlEditorLines,
  sqlEditorActiveLineTop,
  sqlFindMatches,
  sqlFindSummary,
  syncSqlEditorState,
  openSqlFind,
  closeSqlFind,
  toggleSqlFindReplace,
  handleSqlFindKeydown,
  goToSqlFindMatch,
  replaceCurrentSqlFindMatch,
  replaceAllSqlFindMatches,
  startSqlPaneResize,
  resetSqlPaneSplit,
  databaseWorkspaceStyle,
  dbAiPaneOpen,
  dbAiPaneWidth,
  dbAiPaneResizing,
  dbAiPaneContext,
  dbAiPaneDraft,
  dbAiPaneComposerAction,
  dbAiPaneComposerPlaceholder,
  dbAiPaneMessages,
  dbAiPaneRestoreIssues,
  sqlDiagnose,
  dbAiDialectOptions,
  canToggleDbAiPane,
  dbAiPaneConnection,
  dbAiPaneCatalogOptions,
  dbAiPaneSchemaOptions,
  dbAiPaneRequiresSchema,
  dbAiPaneConnectionNeedsConnect,
  dbAiPaneContextTitle,
  dbAiPaneContextSummary,
  dbAiPaneIsStreaming,
  dbAiPaneCanSend,
  dbAiPaneStatusLabel,
  toggleDbAiPane,
  closeDbAiPane,
  useActiveDbAiPaneContext,
  updateDbAiPaneConnection,
  updateDbAiPaneCatalog,
  updateDbAiPaneSchema,
  connectDbAiPaneConnection,
  retryDbAiPaneBinding,
  handleDbAiPaneDraftKeydown,
  cancelDbAiPaneActionMode,
  sendDbAiPaneQuickPrompt,
  resetDbAiPaneConversation,
  restoreDbAiPaneSession,
  loadOlderDbAiPaneMessages,
  ensureDatabaseWorkspaceSessionReady,
  cancelDbAiPaneResponse,
  sendDbAiPaneMessage,
  startDbAiPaneResize,
  resetDbAiPaneWidth,
  openDbAiFromToolbar,
  copyDbAiSql,
  replaceDbAiSqlSelection,
  insertDbAiSql,
  runDbAiReadonly,
  canRunDbAiPaneMessageSql,
  updateDbAiPaneMessageDialect,
  formatDbAiRequestTime,
  diagnoseSqlError,
  visibleGroupNodes,
  groupRootMoveDisabled,
  groupMoveTargets,
  activeDataWherePending,
  pagedDataRows,
  filteredSqlRows,
  pagedSqlRows,
  connectionUrl,
  markConnectionUrlAuto,
  updateSqlTabConnection,
  updateSqlTabCatalog,
  updateSqlTabSchema,
  updateCreateDatabaseName,
  createDatabaseSql,
  createDatabaseNameError,
  createDatabaseCanSubmit,
  connectionsByGroup,
  selectNode,
  toggleGroup,
  toggleConnection,
  toggleCatalog,
  toggleSchema,
  toggleSchemaObjectFolder,
  toggleTable,
  selectColumnNode,
  openTable,
  closeTab,
  updateActiveSql,
  openSqlConsole,
  runSql,
  runSqlFromShortcut,
  saveActiveSql,
  closeResultTab,
  openSqlHistoryResult,
  isSqlHistoryClosed,
  updateSqlResultActiveTab,
  toggleResultTabPinned,
  updateSqlResultPage,
  updateSqlResultPageSize,
  gotoLastSqlResultPage,
  cycleSqlSort,
  applySqlFilter,
  updateDataPage,
  updateDataPageSize,
  updateActiveDataWhereDraft,
  gotoLastDataPage,
  cycleDataSort,
  applyDataFilter,
  applyWhere,
  canEditDataTab,
  dataEditDisabledReason,
  isDataTabDirty,
  updateDataCell,
  updateNewDataRowCell,
  setActiveDataSelectedRow,
  addDataRow,
  deleteSelectedDataRow,
  undoDataChanges,
  saveDataChanges,
  exportActiveSqlResultPage,
  exportActiveDataPage,
  closeChartModal,
  updateCommentDraft,
  openActiveSqlResultChart,
  openActiveDataChart,
  openActiveSqlResultComment,
  openActiveDataComment,
  saveActiveComment,
  closeCommentModal,
  discardDataChanges,
  copyDataMutationPreview,
  refreshDataTab,
  refreshDataTotal,
  formatSql,
  toggleConnectionStatus,
  refreshConnected,
  toggleAddMenu,
  focusDatabaseSearch,
  clearDatabaseSearch,
  openOverviewEngine,
  openConnectionModalFromEngine,
  addGroup,
  startGroupRename,
  commitGroupRename,
  cancelGroupRename,
  requestDeleteGroup,
  moveGroupTo,
  openContextMenu,
  connectFromMenu,
  moveConnectionToGroup,
  refreshConnectionFromMenu,
  editConnection,
  requestRemoveConnection,
  openContextTable,
  openContextSql,
  openDdlModalFromContext,
  copySelectSql,
  copyTableDdlFromContext,
  requestDangerousTableAction,
  cancelDangerousTableAction,
  updateDangerConfirmText,
  confirmDangerousTableAction,
  cancelOperationConfirm,
  confirmOperation,
  copyContextName,
  closeConnectionModal,
  openSshProxyConfigFromConnectionModal,
  pickSqliteFile,
  testConnectionDraft,
  saveConnectionDraft,
  openCreateDatabaseModal,
  closeCreateDatabaseModal,
  createDatabase,
  copyDdl,
  closeDdlModal,
  engineAccent,
  engineName,
  closeContextSubmenuSoon
} = useDatabaseWorkspaceRuntime()

let latestProductSessionRequestSequence = 0

const showProductSessionFailure = (request: ProductSessionUiRequest) => {
  const key = request.action === 'create'
    ? 'agents.sessionCreateFailed'
    : request.action === 'focus'
      ? 'agents.sessionFocusFailed'
      : 'agents.sessionRestoreFailed'
  workspace.setTopNotice(t(key))
}

const applyDatabaseProductSessionRequest = async (request: ProductSessionUiRequest) => {
  await ensureDatabaseWorkspaceSessionReady()
  if (request.sequence !== latestProductSessionRequestSequence) return
  if (request.action === 'create') {
    if (!dbAiPaneOpen.value) toggleDbAiPane()
    if (!resetDbAiPaneConversation()) showProductSessionFailure(request)
    return
  }
  if (!request.sessionId || !(await restoreDbAiPaneSession(request.sessionId))) {
    if (request.sequence === latestProductSessionRequestSequence) showProductSessionFailure(request)
  }
}

watch(
  () => props.productSessionRequest,
  (request) => {
    if (
      !request ||
      request.surface !== 'database' ||
      request.sequence === latestProductSessionRequestSequence
    ) return
    latestProductSessionRequestSequence = request.sequence
    emit('productSessionRequestConsumed', request.sequence)
    void applyDatabaseProductSessionRequest(request)
  },
  { immediate: true, flush: 'post' }
)
</script>
