import { computed, ref, watch } from 'vue'
import { createDatabaseCatalogConnectionWorkspaceController } from '@/services/database/databaseCatalogConnectionWorkspaceController'
import { createDatabaseAiWorkspaceController } from '@/services/database/databaseAiWorkspaceController'
import { dbAiResponseLanguageForLocale } from '@/services/database/databaseAiRuntime'
import { createDatabaseSqlDataWorkspaceController } from '@/services/database/databaseSqlDataWorkspaceController'
import { createDatabaseSqlEditorWorkspaceController } from '@/services/database/databaseSqlEditorWorkspaceController'
import { createDatabaseWorkspaceCatalogRuntime } from '@/services/database/databaseWorkspaceCatalogRuntime'
import { createDatabaseWorkspaceConnectionStateRuntime } from '@/services/database/databaseWorkspaceConnectionStateRuntime'
import { createDatabaseWorkspaceShellRuntime } from '@/services/database/databaseWorkspaceShellRuntime'
import { createDatabaseWorkspaceSqlTabRuntime } from '@/services/database/databaseWorkspaceSqlTabRuntime'
import type { DatabaseMainWorkspaceApi } from '@/components/database/databaseMainWorkspaceTypes'
import { makeDirtyState } from '@/services/database/databaseGridRuntime'
import {
  DB_AI_PANE_MAX_WIDTH,
  DB_AI_PANE_MIN_WIDTH,
  DEFAULT_GROUP_ID
} from '@/services/database/databaseWorkspaceRuntime'
import type {
  ContextMenu,
  ContextSubmenu,
  WorkspaceTab
} from '@/services/database/databaseWorkspaceTypes'
import { useWorkspaceStore } from '@/stores/workspace'
import { resolveLocale } from '@/i18n/runtime'

export const useDatabaseWorkspaceRuntime = () => {

  const workspaceStore = useWorkspaceStore()
  const databaseAiResponseLanguage = computed(() => dbAiResponseLanguageForLocale(
    resolveLocale(workspaceStore.config.language, typeof navigator === 'undefined' ? [] : navigator.languages || [navigator.language])
  ))

  const overflowOpen = ref(false)
  const addMenuOpen = ref(false)
  const addMenuPosition = ref({ x: 0, y: 0 })
  const contextMenu = ref<ContextMenu | null>(null)
  const contextSubmenu = ref<ContextSubmenu>(null)
  const editingGroupId = ref<string | null>(null)
  const editingGroupName = ref('')

  const tabs = ref<WorkspaceTab[]>([{ id: 'tab-overview', kind: 'overview', title: 'Overview' }])
  const activeTabId = ref('tab-overview')
  const sqlEditorRef = ref<DatabaseMainWorkspaceApi | null>(null)

  const databaseAiPanelsRef = ref<{ scrollPaneMessagesToBottom: () => void } | null>(null)

  const activeTab = computed(() => tabs.value.find((tab) => tab.id === activeTabId.value))
  const activeSqlTab = computed(() => (activeTab.value?.kind === 'sql' ? activeTab.value : null))
  const activeDataTab = computed(() => (activeTab.value?.kind === 'data' ? activeTab.value : null))

  const shellRuntime = createDatabaseWorkspaceShellRuntime(
    {
      editingGroupId,
      editorSettings: computed(() => workspaceStore.editorSettings)
    }
  )
  const {
    notice,
    showNotice,
    copyText,
    createWorkspaceStyle,
    registerLifecycle
  } = shellRuntime

  const markDataTabMissing = (tab: Extract<WorkspaceTab, { kind: 'data' }>, message: string) => {
    tab.error = message
    tab.rows = []
    tab.rowCount = 0
    tab.total = 0
    tab.dirtyState = makeDirtyState([], tab.primaryKey)
    tab.undoStack = []
    resetDataMutationPlan(tab)
  }

  const catalogRuntime = createDatabaseWorkspaceCatalogRuntime({
    tabs,
    activeTab,
    activeSqlTab
  }, {
    showNotice,
    errorToMessage,
    markDataTabMissing,
    syncCatalogDependents: () => syncDbAiPaneContextAfterCatalogChange()
  })

  const {
    databaseEngines,
    groups,
    groupParentById,
    connections,
    keyword,
    sidebarCollapsed,
    databaseSidebarTreeRef,
    expandedGroups,
    expandedConnections,
    expandedCatalogs,
    expandedSchemas,
    expandedSchemaObjectFolders,
    expandedTables,
    selectedNodeId,
    activeSqlCanRun,
    currentSqlCatalogs,
    currentSqlSchemas,
    activeSqlRequiresSchema,
    visibleGroupNodes,
    connectionsByGroup,
    selectNode,
    toggleGroup,
    toggleConnection,
    toggleCatalog,
    toggleSchema,
    toggleSchemaObjectFolder,
    toggleTable,
    selectColumnNode,
    findConnection,
    findTable,
    tableContextMatches,
    databaseNodeExists,
    repairTabsForConnection,
    applySqlTabConnectionContext,
    applyDatabaseCatalog,
    loadDatabaseCatalog,
    databaseCatalogMutationData,
    applyDatabaseCatalogMutationResult,
    resolveSqlConsoleContext,
    defaultSqlContextForConnection,
    updateSqlTabCatalog,
    updateSqlTabSchema,
    renderDefaultSql
  } = catalogRuntime

  const connectionStateRuntime = createDatabaseWorkspaceConnectionStateRuntime({
    connections,
    groups,
    groupParentById,
    contextMenu,
    sshProxyConfigs: computed(() => workspaceStore.sshProxyConfigs)
  })
  const {
    connectionModalOpen,
    connectionModalMode,
    connectionFeedback,
    connectionFeedbackKind,
    connectionErrors,
    connectionUrlDirty,
    passwordVisible,
    connectionTesting,
    connectionSaving,
    postgresSslModeOptions,
    connectionDraft,
    createDatabaseModal,
    ddlModal,
    dangerConfirm,
    operationConfirm,
    databaseSshProxyOptions,
    databaseSshProxyNames,
    contextConnectionConnected,
    contextConnectionCanCreateDatabase,
    connectionMoveTargets,
    connectionRootMoveDisabled,
    groupRootMoveDisabled,
    groupMoveTargets
  } = connectionStateRuntime

  const {
    activeSqlHasText,
    activeSqlSaving,
    activeSqlIsDirty,
    activeSqlSaveTitle,
    activeSqlSaveStateText,
    closeTab,
    openSqlConsole,
    updateSqlTabConnection
  } = createDatabaseWorkspaceSqlTabRuntime(
    {
      tabs,
      activeTabId,
      activeSqlTab,
      expandedConnections
    },
    {
      showNotice,
      closeMenus: () => closeMenus(),
      findConnection,
      resolveSqlConsoleContext,
      applyDatabaseCatalogMutationResult,
      applySqlTabConnectionContext,
      connectConnection: (connectionId: string) => connectDatabaseConnectionViaBackend(connectionId)
    }
  )

  const {
    SQL_PANE_MIN_PERCENT,
    SQL_PANE_MAX_PERCENT,
    sqlPaneEditorPercent,
    sqlPaneResizing,
    sqlEditorScrollTop,
    sqlEditorActiveLine,
    sqlEditorActiveColumn,
    sqlEditorSelectionSize,
    sqlFindOpen,
    sqlFindReplaceOpen,
    sqlFindQuery,
    sqlFindReplace,
    sqlFindCaseSensitive,
    sqlEditorLineHeight,
    sqlPaneStyle,
    activeSqlEditorLineCount,
    activeSqlEditorLines,
    sqlEditorActiveLineTop,
    sqlFindMatches,
    sqlFindSummary,
    getSelectedSqlText,
    getSqlCursorOffset,
    getSqlSelectionRange,
    getSqlTextUntilCursor,
    syncSqlEditorState,
    setEditorSql,
    openSqlFind,
    closeSqlFind,
    toggleSqlFindReplace,
    handleSqlFindKeydown,
    goToSqlFindMatch,
    replaceCurrentSqlFindMatch,
    replaceAllSqlFindMatches,
    startSqlPaneResize,
    stopSqlPaneResize,
    resetSqlPaneSplit
  } = createDatabaseSqlEditorWorkspaceController(
    {
      activeSqlTab,
      sqlEditorRef,
      editorSettings: computed(() => workspaceStore.editorSettings)
    },
    {
      showNotice
    }
  )
  const {
    chartModal,
    commentModal,
    activeDataEditSummary,
    activeSqlResult,
    activeSqlResultViewState,
    activeDataWherePending,
    pagedDataRows,
    filteredSqlRows,
    pagedSqlRows,
    openTable,
    updateActiveSql,
    runSql,
    appendSqlExecution,
    runSqlFromShortcut,
    saveActiveSql,
    closeResultTab,
    openSqlHistoryResult,
    isSqlHistoryClosed,
    updateSqlResultActiveTab,
    toggleResultTabPinned,
    updateSqlResultPage,
    updateSqlResultPageSize,
    gotoLastSqlResultPage,
    cycleSqlSort,
    applySqlFilter,
    updateDataPage,
    updateDataPageSize,
    updateActiveDataWhereDraft,
    gotoLastDataPage,
    cycleDataSort,
    applyDataFilter,
    applyWhere,
    canEditDataTab,
    dataEditDisabledReason,
    isDataTabDirty,
    resetDataMutationPlan,
    refreshDataMutationPlan,
    updateDataCell,
    updateNewDataRowCell,
    setActiveDataSelectedRow,
    addDataRow,
    deleteSelectedDataRow,
    undoDataChanges,
    saveDataChanges,
    mutateDatabaseTableThroughBackend,
    exportActiveSqlResultPage,
    exportActiveDataPage,
    closeChartModal,
    updateCommentDraft,
    openActiveSqlResultChart,
    openActiveDataChart,
    openActiveSqlResultComment,
    openActiveDataComment,
    saveActiveComment,
    closeCommentModal,
    discardDataChanges,
    copyDataMutationPreview,
    refreshDataTab,
    refreshDataTotal,
    reloadDataTab,
    formatSql,
    cleanupDroppedTableUi,
    dataTabsMatching,
    tabIdsMatching
  } = createDatabaseSqlDataWorkspaceController(
    {
      tabs,
      activeTabId,
      activeSqlTab,
      activeDataTab,
      activeSqlCanRun
    },
    {
      showNotice,
      copyText,
      bridgeErrorMessage,
      errorToMessage,
      findConnection,
      findTable,
      tableContextMatches,
      getSelectedSqlText,
      getSqlCursorOffset,
      getSqlSelectionRange,
      setEditorSql
    }
  )
  const {
    dbAiPaneOpen,
    dbAiPaneWidth,
    dbAiPaneResizing,
    dbAiPaneContext,
    dbAiPaneDraft,
    dbAiPaneComposerAction,
    dbAiPaneComposerPlaceholder,
    dbAiPaneMessages,
    dbAiOpen,
    dbAiActiveReqId,
    sqlDiagnose,
    dbAiDialectOptions,
    canToggleDbAiPane,
    dbAiPaneConnection,
    dbAiPaneCatalogOptions,
    dbAiPaneSchemaOptions,
    dbAiPaneRequiresSchema,
    dbAiPaneConnectionNeedsConnect,
    dbAiPaneContextTitle,
    dbAiPaneContextSummary,
    dbAiPaneIsStreaming,
    dbAiPaneCanSend,
    dbAiRequestList,
    dbAiTargetDialect,
    dbAiActionLabel,
    dbAiStatus,
    dbAiContextSummary,
    dbAiIsConvertAction,
    dbAiReasoningText,
    dbAiContentText,
    dbAiEmptyState,
    dbAiSql,
    dbAiIsExecutableDialect,
    dbAiCanRunReadOnly,
    dbAiCanCancel,
    dbAiStatusLabel,
    dbAiPaneStatusLabel,
    syncDbAiPaneContextAfterActiveTabChange,
    syncDbAiPaneContextAfterCatalogChange,
    toggleDbAiPane,
    closeDbAiPane,
    useActiveDbAiPaneContext,
    updateDbAiPaneConnection,
    updateDbAiPaneCatalog,
    updateDbAiPaneSchema,
    connectDbAiPaneConnection,
    handleDbAiPaneDraftKeydown,
    cancelDbAiPaneActionMode,
    sendDbAiPaneQuickPrompt,
    resetDbAiPaneConversation,
    cancelDbAiPaneResponse,
    sendDbAiPaneMessage,
    startDbAiPaneResize,
    stopDbAiPaneResize,
    resetDbAiPaneWidth,
    loadDbAiPaneState,
    persistDbAiPaneState,
    openDbAiFromToolbar,
    openDbAi,
    setActiveDbAiRequest,
    copyDbAiSql,
    replaceDbAiSqlSelection,
    insertDbAiSql,
    runDbAiReadonly,
    canRunDbAiPaneMessageSql,
    updateDbAiPaneMessageDialect,
    cancelDbAiRequest,
    clearDbAiRequest,
    formatDbAiRequestTime,
    clearSqlDiagnoseTimers,
    diagnoseSqlError
  } = createDatabaseAiWorkspaceController(
    {
      connections,
      expandedConnections,
      activeSqlTab,
      activeSqlCanRun,
      currentSqlCatalogs,
      responseLanguage: databaseAiResponseLanguage,
      databaseAiPanelsRef
    },
    {
      showNotice,
      closeMenus: () => closeMenus(),
      bridgeErrorMessage,
      copyText,
      findConnection,
      defaultSqlContextForConnection,
      resolveSqlConsoleContext,
      connectConnection: (connectionId: string) => connectDatabaseConnectionForDbAi(connectionId),
      getSelectedSqlText,
      getSqlCursorOffset,
      getSqlSelectionRange,
      getSqlTextUntilCursor,
      renderDefaultSql,
      setEditorSql,
      appendSqlExecution
    }
  )

  watch(activeTabId, () => {
    syncDbAiPaneContextAfterActiveTabChange()
  })

  function errorToMessage(error: unknown) {
    if (error instanceof Error) return error.message
    if (typeof error === 'string') return error
    return 'Backend SQL executor failed.'
  }

  function bridgeErrorMessage(error: unknown, fallback: string) {
    if (error instanceof Error && error.message.trim()) return error.message
    if (typeof error === 'string' && error.trim()) return error.trim()
    return fallback
  }

  const databaseCatalogConnectionHooks = {
    openTable,
    mutateDatabaseTableThroughBackend,
    dataTabsMatching,
    reloadDataTab,
    tabIdsMatching,
    cleanupDroppedTableUi,
    openDbAi: ((...args: Parameters<typeof openDbAi>) => openDbAi(...args)) as typeof openDbAi
  }

  const {
    toggleConnectionStatus,
    refreshConnected,
    toggleAddMenu,
    focusDatabaseSearch,
    clearDatabaseSearch,
    openOverviewEngine,
    openConnectionModalFromEngine,
    addGroup,
    startGroupRename,
    commitGroupRename,
    cancelGroupRename,
    requestDeleteGroup,
    moveGroupTo,
    openContextMenu,
    connectFromMenu,
    moveConnectionToGroup,
    refreshConnectionFromMenu,
    editConnection,
    requestRemoveConnection,
    openContextTable,
    openContextSql,
    openDdlModalFromContext,
    copySelectSql,
    copyTableDdlFromContext,
    requestDangerousTableAction,
    cancelDangerousTableAction,
    updateDangerConfirmText,
    confirmDangerousTableAction,
    cancelOperationConfirm,
    confirmOperation,
    copyContextName,
    databaseProxyAvailable,
    connectionUrl,
    createDatabaseSql,
    createDatabaseNameError,
    createDatabaseCanSubmit,
    markConnectionUrlAuto,
    updateCreateDatabaseName,
    closeConnectionModal,
    openSshProxyConfigFromConnectionModal,
    pickSqliteFile,
    testConnectionDraft,
    saveConnectionDraft,
    openCreateDatabaseModal,
    closeCreateDatabaseModal,
    createDatabase,
    copyDdl,
    closeDdlModal,
    engineAccent,
    engineName,
    closeMenus,
    closeContextSubmenuSoon,
    connectDatabaseConnectionViaBackend,
    disconnectDatabaseConnectionViaBackend,
    refreshDatabaseConnectionViaBackend,
    connectDatabaseConnectionForDbAi
  } = createDatabaseCatalogConnectionWorkspaceController(
    {
      databaseEngines,
      groups,
      groupParentById,
      connections,
      keyword,
      sidebarCollapsed,
      databaseSidebarTreeRef,
      expandedGroups,
      expandedConnections,
      expandedCatalogs,
      expandedSchemas,
      expandedSchemaObjectFolders,
      expandedTables,
      selectedNodeId,
      overflowOpen,
      addMenuOpen,
      addMenuPosition,
      contextMenu,
      contextSubmenu,
      editingGroupId,
      editingGroupName,
      tabs,
      activeTabId,
      activeSqlTab,
      connectionModalOpen,
      connectionModalMode,
      connectionFeedback,
      connectionFeedbackKind,
      connectionErrors,
      connectionUrlDirty,
      passwordVisible,
      connectionTesting,
      connectionSaving,
      connectionDraft,
      createDatabaseModal,
      ddlModal,
      dangerConfirm,
      operationConfirm,
      databaseSshProxyOptions,
      databaseSshProxyNames
    },
    {
      workspaceStore,
      showNotice,
      copyText,
      errorToMessage,
      findConnection,
      applyDatabaseCatalog,
      applyDatabaseCatalogMutationResult,
      databaseCatalogMutationData,
      databaseNodeExists,
      repairTabsForConnection,
      findTable,
      openSqlConsole,
      renderDefaultSql
    },
    databaseCatalogConnectionHooks
  )

  const databaseWorkspaceStyle = createWorkspaceStyle({
    dbAiPaneOpen,
    dbAiPaneWidth,
    sqlEditorLineHeight
  })

  registerLifecycle({
    loadDatabaseCatalog,
    loadDbAiPaneState,
    closeMenus,
    stopSqlPaneResize,
    stopDbAiPaneResize,
    clearSqlDiagnoseTimers,
    persistDbAiPaneState
  })

  return {
    DB_AI_PANE_MIN_WIDTH,
    DB_AI_PANE_MAX_WIDTH,
    DEFAULT_GROUP_ID,
    databaseEngines,
    groups,
    connections,
    keyword,
    sidebarCollapsed,
    databaseSidebarTreeRef,
    expandedGroups,
    expandedConnections,
    expandedCatalogs,
    expandedSchemas,
    expandedSchemaObjectFolders,
    expandedTables,
    selectedNodeId,
    overflowOpen,
    addMenuOpen,
    addMenuPosition,
    contextMenu,
    contextSubmenu,
    notice,
    editingGroupId,
    editingGroupName,
    tabs,
    activeTabId,
    sqlEditorRef,
    connectionModalOpen,
    connectionModalMode,
    connectionFeedback,
    connectionFeedbackKind,
    connectionErrors,
    passwordVisible,
    connectionTesting,
    connectionSaving,
    postgresSslModeOptions,
    connectionDraft,
    createDatabaseModal,
    ddlModal,
    chartModal,
    commentModal,
    databaseAiPanelsRef,
    dangerConfirm,
    operationConfirm,
    activeTab,
    activeSqlTab,
    activeDataTab,
    activeDataEditSummary,
    activeSqlCanRun,
    currentSqlCatalogs,
    currentSqlSchemas,
    activeSqlRequiresSchema,
    databaseSshProxyOptions,
    databaseProxyAvailable,
    contextConnectionConnected,
    contextConnectionCanCreateDatabase,
    connectionMoveTargets,
    connectionRootMoveDisabled,
    activeSqlResult,
    activeSqlResultViewState,
    activeSqlHasText,
    activeSqlSaving,
    activeSqlIsDirty,
    activeSqlSaveTitle,
    activeSqlSaveStateText,
    SQL_PANE_MIN_PERCENT,
    SQL_PANE_MAX_PERCENT,
    sqlPaneEditorPercent,
    sqlPaneResizing,
    sqlEditorScrollTop,
    sqlEditorActiveLine,
    sqlEditorActiveColumn,
    sqlEditorSelectionSize,
    sqlFindOpen,
    sqlFindReplaceOpen,
    sqlFindQuery,
    sqlFindReplace,
    sqlFindCaseSensitive,
    sqlPaneStyle,
    activeSqlEditorLineCount,
    activeSqlEditorLines,
    sqlEditorActiveLineTop,
    sqlFindMatches,
    sqlFindSummary,
    syncSqlEditorState,
    openSqlFind,
    closeSqlFind,
    toggleSqlFindReplace,
    handleSqlFindKeydown,
    goToSqlFindMatch,
    replaceCurrentSqlFindMatch,
    replaceAllSqlFindMatches,
    startSqlPaneResize,
    resetSqlPaneSplit,
    databaseWorkspaceStyle,
    dbAiPaneOpen,
    dbAiPaneWidth,
    dbAiPaneResizing,
    dbAiPaneContext,
    dbAiPaneDraft,
    dbAiPaneComposerAction,
    dbAiPaneComposerPlaceholder,
    dbAiPaneMessages,
    dbAiOpen,
    dbAiActiveReqId,
    sqlDiagnose,
    dbAiDialectOptions,
    canToggleDbAiPane,
    dbAiPaneConnection,
    dbAiPaneCatalogOptions,
    dbAiPaneSchemaOptions,
    dbAiPaneRequiresSchema,
    dbAiPaneConnectionNeedsConnect,
    dbAiPaneContextTitle,
    dbAiPaneContextSummary,
    dbAiPaneIsStreaming,
    dbAiPaneCanSend,
    dbAiRequestList,
    dbAiTargetDialect,
    dbAiActionLabel,
    dbAiStatus,
    dbAiContextSummary,
    dbAiIsConvertAction,
    dbAiReasoningText,
    dbAiContentText,
    dbAiEmptyState,
    dbAiSql,
    dbAiIsExecutableDialect,
    dbAiCanRunReadOnly,
    dbAiCanCancel,
    dbAiStatusLabel,
    dbAiPaneStatusLabel,
    toggleDbAiPane,
    closeDbAiPane,
    useActiveDbAiPaneContext,
    updateDbAiPaneConnection,
    updateDbAiPaneCatalog,
    updateDbAiPaneSchema,
    connectDbAiPaneConnection,
    handleDbAiPaneDraftKeydown,
    cancelDbAiPaneActionMode,
    sendDbAiPaneQuickPrompt,
    resetDbAiPaneConversation,
    cancelDbAiPaneResponse,
    sendDbAiPaneMessage,
    startDbAiPaneResize,
    resetDbAiPaneWidth,
    openDbAiFromToolbar,
    setActiveDbAiRequest,
    copyDbAiSql,
    replaceDbAiSqlSelection,
    insertDbAiSql,
    runDbAiReadonly,
    canRunDbAiPaneMessageSql,
    updateDbAiPaneMessageDialect,
    cancelDbAiRequest,
    clearDbAiRequest,
    formatDbAiRequestTime,
    diagnoseSqlError,
    visibleGroupNodes,
    groupRootMoveDisabled,
    groupMoveTargets,
    activeDataWherePending,
    pagedDataRows,
    filteredSqlRows,
    pagedSqlRows,
    connectionUrl,
    markConnectionUrlAuto,
    updateSqlTabConnection,
    updateSqlTabCatalog,
    updateSqlTabSchema,
    updateCreateDatabaseName,
    createDatabaseSql,
    createDatabaseNameError,
    createDatabaseCanSubmit,
    connectionsByGroup,
    selectNode,
    toggleGroup,
    toggleConnection,
    toggleCatalog,
    toggleSchema,
    toggleSchemaObjectFolder,
    toggleTable,
    selectColumnNode,
    openTable,
    closeTab,
    updateActiveSql,
    openSqlConsole,
    runSql,
    runSqlFromShortcut,
    saveActiveSql,
    closeResultTab,
    openSqlHistoryResult,
    isSqlHistoryClosed,
    updateSqlResultActiveTab,
    toggleResultTabPinned,
    updateSqlResultPage,
    updateSqlResultPageSize,
    gotoLastSqlResultPage,
    cycleSqlSort,
    applySqlFilter,
    updateDataPage,
    updateDataPageSize,
    updateActiveDataWhereDraft,
    gotoLastDataPage,
    cycleDataSort,
    applyDataFilter,
    applyWhere,
    canEditDataTab,
    dataEditDisabledReason,
    isDataTabDirty,
    updateDataCell,
    updateNewDataRowCell,
    setActiveDataSelectedRow,
    addDataRow,
    deleteSelectedDataRow,
    undoDataChanges,
    saveDataChanges,
    exportActiveSqlResultPage,
    exportActiveDataPage,
    closeChartModal,
    updateCommentDraft,
    openActiveSqlResultChart,
    openActiveDataChart,
    openActiveSqlResultComment,
    openActiveDataComment,
    saveActiveComment,
    closeCommentModal,
    discardDataChanges,
    copyDataMutationPreview,
    refreshDataTab,
    refreshDataTotal,
    formatSql,
    toggleConnectionStatus,
    refreshConnected,
    toggleAddMenu,
    focusDatabaseSearch,
    clearDatabaseSearch,
    openOverviewEngine,
    openConnectionModalFromEngine,
    addGroup,
    startGroupRename,
    commitGroupRename,
    cancelGroupRename,
    requestDeleteGroup,
    moveGroupTo,
    openContextMenu,
    connectFromMenu,
    moveConnectionToGroup,
    refreshConnectionFromMenu,
    editConnection,
    requestRemoveConnection,
    openContextTable,
    openContextSql,
    openDdlModalFromContext,
    copySelectSql,
    copyTableDdlFromContext,
    requestDangerousTableAction,
    cancelDangerousTableAction,
    updateDangerConfirmText,
    confirmDangerousTableAction,
    cancelOperationConfirm,
    confirmOperation,
    copyContextName,
    closeConnectionModal,
    openSshProxyConfigFromConnectionModal,
    pickSqliteFile,
    testConnectionDraft,
    saveConnectionDraft,
    openCreateDatabaseModal,
    closeCreateDatabaseModal,
    createDatabase,
    copyDdl,
    closeDdlModal,
    engineAccent,
    engineName,
    closeContextSubmenuSoon
  }
}
