import { BrowserWindow, type IpcMain, type IpcMainInvokeEvent, type OpenDialogOptions as ElectronOpenDialogOptions, type SaveDialogOptions as ElectronSaveDialogOptions } from 'electron'
import { basename, isAbsolute, join } from 'path'
import { readFile, stat, writeFile } from 'fs/promises'
import { broadcastWindowEvent } from '@shared/windowEvents'
import { stageChatAttachment } from '../backend/chat/chatAttachments'
import {
  prepareChatImageAttachment,
  prepareChatImageAttachmentFromClipboard,
  prepareChatImageAttachmentFromFile,
  validateChatImageAttachment
} from '../backend/chat/chatImageAttachment'
import { saveCustomBackgroundFile, saveCustomNotificationSoundFile, writeLocalTextFile } from '../backend/files/localFileWrites'
import {
  configureLocalEditorFilesRuntime,
  readLocalEditorFile,
  startLocalEditorFileWatch,
  stopLocalEditorFileWatch,
  writeLocalEditorFile
} from '../backend/files/localEditorFiles'
import type {
  ChatImageAttachmentClipboardInput,
  ChatImageAttachmentFileInput,
  ChatImageAttachmentPrepareInput,
  ChatImageAttachmentValidateInput,
  LocalEditorFileWatchInput,
  LocalEditorFileWriteInput,
  OpenDialogOptions,
  SaveDialogOptions
} from '@shared/contracts/localFiles'

type DialogResult = { canceled?: boolean; filePaths?: string[]; filePath?: string }
type WriteFixtureFile = (filePath: string, content: string | Buffer, encoding?: BufferEncoding) => Promise<void>
type OpenDialogProperty = NonNullable<OpenDialogOptions['properties']>[number]

type RegisterLocalFilesIpcInput = {
  showOpenDialog: (event: IpcMainInvokeEvent, options: ElectronOpenDialogOptions) => Promise<DialogResult | undefined>
  showSaveDialog: (event: IpcMainInvokeEvent, options: ElectronSaveDialogOptions) => Promise<DialogResult | undefined>
  shouldUseE2eDialogFixtures: () => boolean
  getUserDataPath: () => string
  getDownloadsPath: () => string
  getChatAttachmentsPath: () => string
  getCustomBackgroundsPath: () => string
  getCustomNotificationSoundsPath: () => string
  customBackgroundUrlForPath: (filePath: string) => string
  writeFixtureFile?: WriteFixtureFile
}

const maxCustomBackgroundBytes = 20 * 1024 * 1024
const maxCustomNotificationSoundBytes = 10 * 1024 * 1024
const maxLocalTextReadBytes = 2 * 1024 * 1024
const allowedCustomBackgroundExtensions = new Set(['.jpg', '.jpeg', '.png', '.gif', '.webp'])
const allowedCustomNotificationSoundExtensions = new Set(['.mp3', '.wav', '.ogg', '.m4a', '.aac', '.flac', '.webm'])

const hasOpenProperty = (options: OpenDialogOptions | undefined, property: string) =>
  Array.isArray(options?.properties) && options.properties.includes(property as OpenDialogProperty)

const hasFilterNamed = (options: OpenDialogOptions | undefined, name: string) =>
  Array.isArray(options?.filters) && options.filters.some((filter) => filter?.name === name)

const writeFixture = async (input: RegisterLocalFilesIpcInput, filePath: string, content: string | Buffer) => {
  const writeFixtureFile: WriteFixtureFile =
    input.writeFixtureFile ||
    (async (targetPath, targetContent, encoding) => {
      if (typeof targetContent === 'string') {
        await writeFile(targetPath, targetContent, encoding || 'utf-8')
        return
      }
      await writeFile(targetPath, targetContent)
    })
  if (typeof content === 'string') {
    await writeFixtureFile(filePath, content, 'utf-8')
  } else {
    await writeFixtureFile(filePath, content)
  }
  return { canceled: false, filePaths: [filePath] }
}

const e2eOpenDialogFixture = async (input: RegisterLocalFilesIpcInput, options: OpenDialogOptions | undefined) => {
  if (!input.shouldUseE2eDialogFixtures()) return undefined
  if (hasOpenProperty(options, 'openFile') && hasFilterNamed(options, 'Asset Import Files')) {
    const assetImportPath = join(input.getUserDataPath(), 'e2e-external-reference-assets.json')
    return writeFixture(
      input,
      assetImportPath,
      JSON.stringify([{ username: 'ops', ip: '10.73.0.9', label: 'e2e-imported-json', group_name: 'E2E', port: 2299 }])
    )
  }
  if (hasOpenProperty(options, 'openFile') && hasFilterNamed(options, 'Key Files')) {
    return writeFixture(input, join(input.getUserDataPath(), 'e2e-import-rsa.pem'), '-----BEGIN RSA PRIVATE KEY-----\ne2e import\n-----END RSA PRIVATE KEY-----')
  }
  if (hasOpenProperty(options, 'openFile') && hasFilterNamed(options, 'Images')) {
    const png1x1 = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/p9sAAAAASUVORK5CYII=', 'base64')
    return writeFixture(input, join(input.getUserDataPath(), 'e2e-background.png'), png1x1)
  }
  if (hasOpenProperty(options, 'openFile') && hasFilterNamed(options, 'Text')) {
    return writeFixture(input, join(input.getUserDataPath(), 'e2e-chat-attachment.md'), '# E2E chat attachment\n\nGenerated by the aiopsterm test harness.\n')
  }
  if (hasOpenProperty(options, 'openFile') && hasFilterNamed(options, 'YAML Files')) {
    const kubeconfigPath = join(input.getUserDataPath(), 'e2e-kubeconfig.yaml')
    return writeFixture(
      input,
      kubeconfigPath,
      [
        'apiVersion: v1',
        'kind: Config',
        'current-context: e2e/admin',
        'clusters:',
        '- name: e2e-cluster',
        '  cluster:',
        '    server: https://e2e.k8s.local:6443',
        'contexts:',
        '- name: e2e/admin',
        '  context:',
        '    cluster: e2e-cluster',
        '    namespace: e2e'
      ].join('\n')
    )
  }
  if (hasOpenProperty(options, 'openDirectory')) {
    return writeFixture(input, join(input.getUserDataPath(), 'e2e-imported-note.md'), '# E2E imported note\n\nGenerated by the aiopsterm test harness.\n')
  }
  return undefined
}

export const registerLocalFilesIpc = (ipcMain: IpcMain, input: RegisterLocalFilesIpcInput) => {
  configureLocalEditorFilesRuntime({
    emitWatchEvent: (event) => broadcastWindowEvent(BrowserWindow.getAllWindows(), 'local-editor-files:watch-event', event)
  })
  ipcMain.handle('dialog:open-file', async (event, options?: OpenDialogOptions) => {
    const fixture = await e2eOpenDialogFixture(input, options)
    if (fixture) return fixture
    return input.showOpenDialog(event, options || {})
  })
  ipcMain.handle('dialog:save-file', async (event, options?: SaveDialogOptions) => {
    if (input.shouldUseE2eDialogFixtures()) {
      return { canceled: false, filePath: join(input.getDownloadsPath(), options?.defaultPath ? basename(String(options.defaultPath)) : 'downloaded-file') }
    }
    return input.showSaveDialog(event, options || {})
  })
  ipcMain.handle('settings:save-custom-background', async (_event, srcAbsPath: string) =>
    saveCustomBackgroundFile(srcAbsPath, {
      backgroundDir: input.getCustomBackgroundsPath(),
      maxBytes: maxCustomBackgroundBytes,
      allowedExtensions: allowedCustomBackgroundExtensions,
      toUrl: input.customBackgroundUrlForPath
    })
  )
  ipcMain.handle('settings:save-custom-notification-sound', async (_event, srcAbsPath: string) =>
    saveCustomNotificationSoundFile(srcAbsPath, {
      soundDir: input.getCustomNotificationSoundsPath(),
      maxBytes: maxCustomNotificationSoundBytes,
      allowedExtensions: allowedCustomNotificationSoundExtensions
    })
  )
  ipcMain.handle('files:read-local', async (_event, filePath: string) => {
    if (!filePath || typeof filePath !== 'string') throw new Error('filePath is required')
    if (!isAbsolute(filePath)) throw new Error('filePath must be absolute')
    const metadata = await stat(filePath)
    if (!metadata.isFile()) throw new Error('Source must be a file')
    if (metadata.size > maxLocalTextReadBytes) throw new Error('File too large')
    return {
      content: await readFile(filePath, 'utf-8'),
      mtimeMs: metadata.mtimeMs,
      size: metadata.size
    }
  })
  ipcMain.handle('files:write-local', async (_event, filePath: string, content: string) => writeLocalTextFile(filePath, content))
  ipcMain.handle('local-editor-files:read', (_event, filePath: string) => readLocalEditorFile(filePath))
  ipcMain.handle('local-editor-files:write', (_event, writeInput: LocalEditorFileWriteInput) => writeLocalEditorFile(writeInput))
  ipcMain.handle('local-editor-files:watch:start', (_event, watchInput: LocalEditorFileWatchInput) => startLocalEditorFileWatch(watchInput))
  ipcMain.handle('local-editor-files:watch:stop', (_event, watchId: string) => stopLocalEditorFileWatch(watchId))
  ipcMain.handle('chat:stage-attachment', async (_event, payload: { taskId: string; srcAbsPath: string }) => stageChatAttachment(payload, input.getChatAttachmentsPath()))
  ipcMain.handle('chat:validate-image-attachment', (_event, validateInput?: ChatImageAttachmentValidateInput) => validateChatImageAttachment(validateInput || {}))
  ipcMain.handle('chat:prepare-image-attachment', (_event, prepareInput?: ChatImageAttachmentPrepareInput) => prepareChatImageAttachment(prepareInput || {}))
  ipcMain.handle('chat:prepare-image-attachment-from-file', (_event, fileInput?: ChatImageAttachmentFileInput) => prepareChatImageAttachmentFromFile(fileInput || {}))
  ipcMain.handle('chat:prepare-image-attachment-from-clipboard', (_event, clipboardInput?: ChatImageAttachmentClipboardInput) =>
    prepareChatImageAttachmentFromClipboard(clipboardInput || {})
  )
}
